<?php
// Auto-generated by `cargo xtask stubs` — do not edit by hand.
// Regenerate with:  cargo xtask stubs

/** @return float */
function celestial_julday(int $year, int $month, int $day, float $hour, int $calendar): float {}

/** @return array */
function celestial_revjul(float $jd, int $calendar): array {}

/** @return int */
function celestial_day_of_week(float $jd): int {}

/** @return float */
function celestial_deltat(float $jd): float {}

/** @return float */
function celestial_sidtime(float $jd_ut): float {}

/** @return void */
function celestial_set_delta_t_userdef(float $dt): void {}

/** @return void */
function celestial_set_ephe_path(string $path): void {}

/** @return void */
function celestial_close(): void {}

/** @return void */
function celestial_set_sid_mode(int $sid_mode, float $t0, float $ayan_t0): void {}

/** @return void */
function celestial_set_topo(float $geolon, float $geolat, float $geoalt): void {}

/** @return string */
function celestial_version(): string {}

/** @return float[] */
function celestial_calc_ut(float $tjdut, int $planet, int $flags): array {}

/** @return float[] */
function celestial_calc(float $tjdet, int $planet, int $flags): array {}

/** @return float[] */
function celestial_nutation(float $jde): array {}

/** @return float */
function celestial_mean_obliquity(float $jde): float {}

/** @return float */
function celestial_true_obliquity(float $jde): float {}

/** @return array */
function celestial_calc_many(float $tjdet, array $planets, int $flags): array {}

/** @return array */
function celestial_calc_ut_many(float $tjdut, array $planets, int $flags): array {}

/** @return float[] */
function celestial_calc_pctr(float $tjdet, int $planet, int $center, int $flags): array {}

/** @return array */
function celestial_fixstar(string $star, float $tjdet, int $flags): array {}

/** @return float */
function celestial_fixstar_mag(string $star): float {}

/** @return array */
function celestial_houses(float $jdut, float $geolat, float $geolon, int $hsys): array {}

/** @return array */
function celestial_houses_ex(float $jdut, int $flags, float $geolat, float $geolon, int $hsys): array {}

/** @return string */
function celestial_house_name(int $hsys): string {}

/** @return float */
function celestial_house_pos(float $armc, float $geolat, float $eps, int $hsys, float $lon, float $lat_body): float {}

/** @return array */
function celestial_sol_eclipse_when_glob(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array */
function celestial_lun_eclipse_when(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array */
function celestial_rise_trans(float $tjdut, int $planet, int $flags, int $event_type, array $geopos, float $pressure_mb, float $temp_c): array {}

/** @return float */
function celestial_norm_deg(float $d): float {}

/** @return int */
function celestial_norm_cs(int $p): int {}

/** @return float */
function celestial_diff_deg_signed(float $p1, float $p2): float {}

/** @return float[] */
function celestial_split_deg(float $deg, int $round_flag): array {}

/** @return float */
function celestial_midpoint_deg(float $x1, float $x0): float {}

/** @return float[] */
function celestial_coord_transform(array $coords, float $eps): array {}

/** @return array */
function celestial_azalt(float $tjdut, int $calc_flag, array $geopos, float $pressure_mb, float $temp_c, array $xin): array {}

/** @return float[] */
function celestial_azalt_rev(float $tjdut, int $calc_flag, array $geopos, float $az, float $alt): array {}

/** @return float */
function celestial_refrac(float $altitude, float $pressure_mb, float $temp_c, int $calc_flag): float {}

/** @return array */
function celestial_sabbats_for_year(int $year): array {}

/** @return float */
function celestial_sabbat_jd(int $year, string $kind): float {}

/** @return array */
function celestial_esbats_for_year(int $year): array {}

/** @return array */
function celestial_match_aspect(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return float|null */
function celestial_next_retro(int $planet, float $jd_start, bool $backward, float $stop_days, int $flags): ?float {}

/** @return int */
function celestial_long_to_rasi(float $lon): int {}

/** @return int */
function celestial_long_to_navamsa(float $lon): int {}

/** @return int[] */
function celestial_long_to_nakshatra(float $lon): array {}

/** @return string|null */
function celestial_nakshatra_name(int $nak): ?string {}

/** @return float[] */
function celestial_raman_houses(float $asc, float $mc, bool $sandhi): array {}

/** @return string|null */
function celestial_sign_name(int $sign): ?string {}

/** @return string|null */
function celestial_format_coord(float $coord, bool $is_latitude): ?string {}

/** @return float|null */
function celestial_parse_coord(string $s): ?float {}

/** @return float */
function celestial_jdnow(): float {}

/** @return string */
function celestial_jd_to_iso_string(float $jd, int $calendar): string {}

/** @return float[] */
function celestial_sign_ingress_ut(int $planet, float $jd, int $flags, bool $backward): array {}

/** @return float */
function celestial_arabic_part(float $asc, float $body2, float $body1): float {}

/** @return float */
function celestial_transit_to_degree(int $planet, float $target_lon, float $jd, int $flags, bool $backward): float {}

/** @return float */
function celestial_mc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_solar_return_jd(float $jd_natal, int $return_year, int $flags): float {}

/** @return float */
function celestial_lunar_return_jd(float $jd_natal, float $jd_start, int $flags): float {}

/** @return float */
function celestial_midpoint(float $lon1, float $lon2): float {}

/** @return int */
function celestial_sign_ruler(int $sign): int {}

/** @return string */
function celestial_zodiac_sign_name(int $sign): string {}

/** @return float[] */
function celestial_lon_to_sign(float $lon): array {}

/** @return float */
function celestial_local_apparent_solar_time(float $jd_ut, float $geolon_deg): float {}

/** @return float[] */
function celestial_annual_profection(array $cusps, int $age): array {}

/** @return array */
function celestial_vimshottari_dasha(float $jd_birth, float $moon_lon_sidereal, float $years_ahead): array {}

/** @return array|null */
function celestial_omer_from_jd(float $jd): ?array {}

/** @return float|null */
function celestial_omer_day_jd(int $hebrew_year, int $day): ?float {}

/** @return float */
function celestial_omer_start_jd(int $hebrew_year): float {}

/** @return array */
function celestial_omer_days(int $hebrew_year): array {}

/** @return string */
function celestial_omer_declaration(int $day): string {}

/** @return array */
function celestial_omer_period(float $jd): array {}

/** @return array */
function celestial_jewish_holidays(int $hebrew_year): array {}

/** @return float|null */
function celestial_jewish_holiday_jd(int $hebrew_year, string $name): ?float {}

/** @return int */
function celestial_hebrew_year_from_jd(float $jd): int {}

/** @return array */
function celestial_jd_to_hebrew_date(float $jd): array {}

/** @return array */
function celestial_easter_gregorian(int $year): array {}

/** @return array */
function celestial_easter_orthodox(int $year): array {}

/** @return float */
function celestial_easter_jd(int $year): float {}

/** @return float */
function celestial_easter_orthodox_jd(int $year): float {}

/** @return array */
function celestial_christian_feasts(int $year): array {}

/** @return array */
function celestial_christian_fixed_feasts(int $year): array {}

/** @return array */
function celestial_hijri_from_jd(float $jd): array {}

/** @return float */
function celestial_hijri_to_jd(int $year, int $month, int $day): float {}

/** @return string */
function celestial_hijri_month_name(int $month): string {}

/** @return array */
function celestial_islamic_observances(int $hijri_year): array {}

/** @return array */
function celestial_panchanga(float $jd): array {}

/** @return array */
function celestial_hindu_festivals(int $gregorian_year): array {}

/** @return float */
function celestial_vesak_jd(int $year): float {}

/** @return array */
function celestial_uposatha_days(int $year): array {}

/** @return float */
function celestial_nowruz_jd(int $year): float {}

/** @return int */
function celestial_gregorian_to_solar_hijri(int $year): int {}

/** @return float */
function celestial_naw_ruz_jd(int $bahai_year): float {}

/** @return array */
function celestial_jd_to_bahai(float $jd): array {}

/** @return array */
function celestial_bahai_holy_days(int $bahai_year): array {}

/** @return string */
function celestial_moon_phase(float $jd): string {}

/** @return float */
function celestial_moon_illumination(float $jd): float {}

/** @return float */
function celestial_moon_elongation(float $jd): float {}

/** @return float */
function celestial_moon_phase_angle(float $jd): float {}

/** @return float */
function celestial_next_new_moon(float $jd_from): float {}

/** @return float */
function celestial_next_first_quarter(float $jd_from): float {}

/** @return float */
function celestial_next_full_moon_phase(float $jd_from): float {}

/** @return float */
function celestial_next_last_quarter(float $jd_from): float {}

/** @return array */
function celestial_moon_phases_for_month(int $year, int $month): array {}

/** @return array */
function celestial_moon_phase_info(float $jd): array {}

/** @return bool */
function celestial_is_day_chart(float $sun_lon, array $cusps): bool {}

/** @return int[] */
function celestial_almuten(float $lon, bool $is_day): array {}

/** @return int */
function celestial_decan_ruler(float $lon): int {}

/** @return int */
function celestial_egyptian_terms_ruler(float $lon): int {}

/** @return int[] */
function celestial_triplicity_rulers(float $lon): array {}

/** @return array */
function celestial_firdaria(float $jd_birth, bool $is_day, float $span_years): array {}

/** @return float[] */
function celestial_solar_term_position(float $sun_lon): array {}

/** @return string[] */
function celestial_sexagenary_name(int $cycle_index): array {}

/** @return string[] */
function celestial_medicine_wheel_totem(float $sun_lon): array {}

/** @return array */
function celestial_secondary_progressions(float $jd_natal, float $years, array $bodies, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return float[] */
function celestial_solar_arc_directions(float $jd_natal, float $years, array $natal_positions, float $natal_mc, int $flags): array {}

/** @return array */
function celestial_midpoint_table(array $positions, float $orb): array {}

/** @return array */
function celestial_calc_chart_aspects(array $positions, array $aspects, float $orb): array {}

/** @return array */
function celestial_calc_chart_aspects_auto(array $positions, array $aspects): array {}

/** @return float[] */
function celestial_monthly_profection(array $cusps, int $age_years, int $age_months): array {}

/** @return float */
function celestial_next_esbat(float $jd_from): float {}

/** @return float[]|null */
function celestial_next_aspect_cusp(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float */
function celestial_ic_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_asc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_dsc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return string[] */
function celestial_four_pillars(float $jd_ut, float $hour_ut, float $sun_lon): array {}

/** @return float[] */
function celestial_antiscion(array $pos, float $axis): array {}

/** @return float */
function celestial_ayanamsa(float $jd_et): float {}

/** @return float */
function celestial_ayanamsa_ut(float $jd_ut): float {}

/** @return string */
function celestial_ayanamsa_name(int $sid_mode): string {}

/** @return string[] */
function celestial_calendar_round(float $jd): array {}

/** @return int[] */
function celestial_degsplit(float $pos): array {}

/** @return string[] */
function celestial_egyptian_decan(float $lon): array {}

/** @return float[] */
function celestial_fixstar2(string $star, float $tjdet, int $flags): array {}

/** @return float */
function celestial_fixstar2_mag(string $star): float {}

/** @return float[] */
function celestial_fixstar2_ut(string $star, float $tjdut, int $flags): array {}

/** @return float[] */
function celestial_fixstar_ut(string $star, float $tjdut, int $flags): array {}

/** @return string[] */
function celestial_full_dignity(int $body, float $lon, bool $is_day): array {}

/** @return int[] */
function celestial_gregorian_to_hijri_years(int $gregorian_year): array {}

/** @return string[] */
function celestial_haab(float $jd): array {}

/** @return string */
function celestial_house_name_str(int $hsys): string {}

/** @return float[] */
function celestial_houses_ex2(float $tjdut, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return int[] */
function celestial_jd_duration(float $jd_start, float $jd_end): array {}

/** @return float[] */
function celestial_lun_eclipse_how(float $jd_ut, int $flags): array {}

/** @return float[] */
function celestial_lun_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function celestial_match_aspect2(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return float[] */
function celestial_match_aspect3(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb): array {}

/** @return float[] */
function celestial_match_aspect4(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb): array {}

/** @return float */
function celestial_mean_sidtime(float $jd): float {}

/** @return float[] */
function celestial_mooncross_node(float $jd_et, int $flags): array {}

/** @return float[] */
function celestial_mooncross_node_ut(float $jd_ut, int $flags): array {}

/** @return int */
function celestial_naisargika_relation(int $gr1, int $gr2): int {}

/** @return float[]|null */
function celestial_next_aspect(int $planet, float $aspect, float $fixed_pt, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_cusp2(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_with(int $planet, float $aspect, int $other, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[] */
function celestial_next_sabbat(float $jd_from): array {}

/** @return float */
function celestial_ochchabala(int $graha, float $sputha): float {}

/** @return int[]|null */
function celestial_parse_datetime(string $s): ?array {}

/** @return string */
function celestial_planet_name(int $planet): string {}

/** @return float[] */
function celestial_refrac_extended(float $altitude, float $geoalt, float $pressure_mb, float $temp_c, float $lapse_rate, int $calc_flag): array {}

/** @return float */
function celestial_residential_strength(float $graha, array $bm): float {}

/** @return float[] */
function celestial_retrograde_station_ut(int $planet, float $jd, int $flags): array {}

/** @return int[] */
function celestial_revjul_hms(float $jd, int $calendar): array {}

/** @return float[] */
function celestial_saturn_4_stars(float $jd, int $flags): array {}

/** @return void */
function celestial_set_jpl_file(string $fname): void {}

/** @return int */
function celestial_sign_ruler_modern(int $sign): int {}

/** @return float[] */
function celestial_sol_eclipse_how(float $jd_ut, array $geopos, int $flags): array {}

/** @return float[] */
function celestial_sol_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function celestial_sol_eclipse_where(float $tjd, int $flags): array {}

/** @return string[] */
function celestial_tonalpohualli(float $jd): array {}

/** @return string[] */
function celestial_tzolkin(float $jd): array {}

/** @return float[] */
function celestial_utc_to_jd(int $year, int $month, int $day, int $hour, int $minute, float $second, int $calendar): array {}

/** @return string[] */
function celestial_xiuhpohualli(float $jd): array {}
