<?php
// Auto-generated by `cargo xtask stubs` — do not edit.
// Regenerate: cargo xtask stubs

/** @var int */
define('SUN', 0);

/** @var int */
define('MOON', 1);

/** @var int */
define('MERCURY', 2);

/** @var int */
define('VENUS', 3);

/** @var int */
define('MARS', 4);

/** @var int */
define('JUPITER', 5);

/** @var int */
define('SATURN', 6);

/** @var int */
define('URANUS', 7);

/** @var int */
define('NEPTUNE', 8);

/** @var int */
define('PLUTO', 9);

/** @var int */
define('MEAN_NODE', 10);

/** @var int */
define('TRUE_NODE', 11);

/** @var int */
define('CHIRON', 15);

/** @var int */
define('GREG_CAL', 1);

/** @var int */
define('JUL_CAL', 0);

/** @var int */
define('FLG_BUILTIN', 2);

/** @var int */
define('FLG_JPL', 1);

/** @var int */
define('FLG_MOSHIER', 4);

/** @var int */
define('FLG_SPEED', 256);

/** @var int */
define('FLG_SIDEREAL', 65536);

/** @var int */
define('FLG_EQUATORIAL', 2048);

/** @var int */
define('FLG_TOPOCTR', 32768);

/** @var int */
define('FLG_HELCTR', 8);

/** @var int */
define('FLG_NONUT', 64);

/** @var int */
define('FLG_RADIANS', 8192);

/** @var int */
define('SIDM_FAGAN_BRADLEY', 0);

/** @var int */
define('SIDM_LAHIRI', 1);

/** @var int */
define('SIDM_RAMAN', 3);

/** @var int */
define('SIDM_KRISHNAMURTI', 5);

/** @var int */
define('SIDM_USER', 255);

/** @var int */
define('ECL_TOTAL', 4);

/** @var int */
define('ECL_ANNULAR', 8);

/** @var int */
define('ECL_PARTIAL', 16);

/** @var int */
define('ECL_PENUMBRAL', 64);

/** @var int */
define('CALC_RISE', 1);

/** @var int */
define('CALC_SET', 2);

/** @var int */
define('TRUE_TO_APP', 0);

/** @var int */
define('APP_TO_TRUE', 1);

/** @var int */
define('SPLIT_DEG_ROUND_SEC', 1);

/** @var int */
define('SPLIT_DEG_ZODIACAL', 8);

/** @var int */
define('SPLIT_DEG_ROUND_MIN', 2);

/** @var int */
define('SPLIT_DEG_ROUND_DEG', 4);

/** @var int */
define('SPLIT_DEG_NAKSHATRA', 1024);

/** @var int */
define('ECL_CENTRAL', 1);

/** @var int */
define('FLG_NOGDEFL', 512);

/** @var int */
define('FLG_NOABERR', 1024);

/** @var int */
define('FLG_XYZ', 4096);

/** @var int */
define('EARTH', 14);

/** @return float */
function julday(int $year, int $month, int $day, float $hour, int $calendar): float {}

/** @return float */
function celestial_julday(int $year, int $month, int $day, float $hour, int $calendar): float {}

/** @return array<string,mixed> */
function revjul(float $jd, int $calendar): array {}

/** @return array<string,mixed> */
function celestial_revjul(float $jd, int $calendar): array {}

/** @return int */
function day_of_week(float $jd): int {}

/** @return int */
function celestial_day_of_week(float $jd): int {}

/** @return float */
function deltat(float $jd): float {}

/** @return float */
function celestial_deltat(float $jd): float {}

/** @return float */
function sidtime(float $jd_ut): float {}

/** @return float */
function celestial_sidtime(float $jd_ut): float {}

/** @return void */
function set_delta_t_userdef(float $dt): void {}

/** @return void */
function celestial_set_delta_t_userdef(float $dt): void {}

/** @return void */
function set_ephe_path(string $path): void {}

/** @return void */
function celestial_set_ephe_path(string $path): void {}

/** @return void */
function close(): void {}

/** @return void */
function celestial_close(): void {}

/** @return void */
function set_sid_mode(int $sid_mode, float $t0, float $ayan_t0): void {}

/** @return void */
function celestial_set_sid_mode(int $sid_mode, float $t0, float $ayan_t0): void {}

/** @return void */
function set_topo(float $geolon, float $geolat, float $geoalt): void {}

/** @return void */
function celestial_set_topo(float $geolon, float $geolat, float $geoalt): void {}

/** @return string */
function version(): string {}

/** @return string */
function celestial_version(): string {}

/** @return float[] */
function calc_ut(float $tjdut, int $planet, int $flags): array {}

/** @return float[] */
function celestial_calc_ut(float $tjdut, int $planet, int $flags): array {}

/** @return float[] */
function calc(float $tjdet, int $planet, int $flags): array {}

/** @return float[] */
function celestial_calc(float $tjdet, int $planet, int $flags): array {}

/** @return float[] */
function nutation(float $jde): array {}

/** @return float[] */
function celestial_nutation(float $jde): array {}

/** @return float */
function mean_obliquity(float $jde): float {}

/** @return float */
function celestial_mean_obliquity(float $jde): float {}

/** @return float */
function true_obliquity(float $jde): float {}

/** @return float */
function celestial_true_obliquity(float $jde): float {}

/** @return array */
function calc_many(float $tjdet, array $planets, int $flags): array {}

/** @return array */
function celestial_calc_many(float $tjdet, array $planets, int $flags): array {}

/** @return array */
function calc_ut_many(float $tjdut, array $planets, int $flags): array {}

/** @return array */
function celestial_calc_ut_many(float $tjdut, array $planets, int $flags): array {}

/** @return float[] */
function calc_pctr(float $tjdet, int $planet, int $center, int $flags): array {}

/** @return float[] */
function celestial_calc_pctr(float $tjdet, int $planet, int $center, int $flags): array {}

/** @return array<string,mixed> */
function fixstar(string $star, float $tjdet, int $flags): array {}

/** @return array<string,mixed> */
function celestial_fixstar(string $star, float $tjdet, int $flags): array {}

/** @return float */
function fixstar_mag(string $star): float {}

/** @return float */
function celestial_fixstar_mag(string $star): float {}

/** @return array<string,mixed> */
function houses(float $jdut, float $geolat, float $geolon, int $hsys): array {}

/** @return array<string,mixed> */
function celestial_houses(float $jdut, float $geolat, float $geolon, int $hsys): array {}

/** @return array<string,mixed> */
function houses_ex(float $jdut, int $flags, float $geolat, float $geolon, int $hsys): array {}

/** @return array<string,mixed> */
function celestial_houses_ex(float $jdut, int $flags, float $geolat, float $geolon, int $hsys): array {}

/** @return string */
function house_name(int $hsys): string {}

/** @return string */
function celestial_house_name(int $hsys): string {}

/** @return float */
function house_pos(float $armc, float $geolat, float $eps, int $hsys, float $lon, float $lat_body): float {}

/** @return float */
function celestial_house_pos(float $armc, float $geolat, float $eps, int $hsys, float $lon, float $lat_body): float {}

/** @return array<string,mixed> */
function sol_eclipse_when_glob(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function celestial_sol_eclipse_when_glob(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function lun_eclipse_when(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function celestial_lun_eclipse_when(float $jd_start, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function rise_trans(float $tjdut, int $planet, int $flags, int $event_type, array $geopos, float $pressure_mb, float $temp_c): array {}

/** @return array<string,mixed> */
function celestial_rise_trans(float $tjdut, int $planet, int $flags, int $event_type, array $geopos, float $pressure_mb, float $temp_c): array {}

/** @return float */
function norm_deg(float $d): float {}

/** @return float */
function celestial_norm_deg(float $d): float {}

/** @return int */
function norm_cs(int $p): int {}

/** @return int */
function celestial_norm_cs(int $p): int {}

/** @return float */
function diff_deg_signed(float $p1, float $p2): float {}

/** @return float */
function celestial_diff_deg_signed(float $p1, float $p2): float {}

/** @return float[] */
function split_deg(float $deg, int $round_flag): array {}

/** @return float[] */
function celestial_split_deg(float $deg, int $round_flag): array {}

/** @return float */
function midpoint_deg(float $x1, float $x0): float {}

/** @return float */
function celestial_midpoint_deg(float $x1, float $x0): float {}

/** @return float[] */
function coord_transform(array $coords, float $eps): array {}

/** @return float[] */
function celestial_coord_transform(array $coords, float $eps): array {}

/** @return array<string,mixed> */
function azalt(float $tjdut, int $calc_flag, array $geopos, float $pressure_mb, float $temp_c, array $xin): array {}

/** @return array<string,mixed> */
function celestial_azalt(float $tjdut, int $calc_flag, array $geopos, float $pressure_mb, float $temp_c, array $xin): array {}

/** @return float[] */
function azalt_rev(float $tjdut, int $calc_flag, array $geopos, float $az, float $alt): array {}

/** @return float[] */
function celestial_azalt_rev(float $tjdut, int $calc_flag, array $geopos, float $az, float $alt): array {}

/** @return float */
function refrac(float $altitude, float $pressure_mb, float $temp_c, int $calc_flag): float {}

/** @return float */
function celestial_refrac(float $altitude, float $pressure_mb, float $temp_c, int $calc_flag): float {}

/** @return array */
function sabbats_for_year(int $year): array {}

/** @return array */
function celestial_sabbats_for_year(int $year): array {}

/** @return float */
function sabbat_jd(int $year, string $kind): float {}

/** @return float */
function celestial_sabbat_jd(int $year, string $kind): float {}

/** @return array */
function esbats_for_year(int $year): array {}

/** @return array */
function celestial_esbats_for_year(int $year): array {}

/** @return array<string,mixed> */
function match_aspect(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return array<string,mixed> */
function celestial_match_aspect(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return float|null */
function next_retro(int $planet, float $jd_start, bool $backward, float $stop_days, int $flags): ?float {}

/** @return float|null */
function celestial_next_retro(int $planet, float $jd_start, bool $backward, float $stop_days, int $flags): ?float {}

/** @return int */
function long_to_rasi(float $lon): int {}

/** @return int */
function celestial_long_to_rasi(float $lon): int {}

/** @return int */
function long_to_navamsa(float $lon): int {}

/** @return int */
function celestial_long_to_navamsa(float $lon): int {}

/** @return int[] */
function long_to_nakshatra(float $lon): array {}

/** @return int[] */
function celestial_long_to_nakshatra(float $lon): array {}

/** @return string|null */
function nakshatra_name(int $nak): ?string {}

/** @return string|null */
function celestial_nakshatra_name(int $nak): ?string {}

/** @return float[] */
function raman_houses(float $asc, float $mc, bool $sandhi): array {}

/** @return float[] */
function celestial_raman_houses(float $asc, float $mc, bool $sandhi): array {}

/** @return string|null */
function sign_name(int $sign): ?string {}

/** @return string|null */
function celestial_sign_name(int $sign): ?string {}

/** @return string|null */
function format_coord(float $coord, bool $is_latitude): ?string {}

/** @return string|null */
function celestial_format_coord(float $coord, bool $is_latitude): ?string {}

/** @return float|null */
function parse_coord(string $s): ?float {}

/** @return float|null */
function celestial_parse_coord(string $s): ?float {}

/** @return float */
function jdnow(): float {}

/** @return float */
function celestial_jdnow(): float {}

/** @return string */
function jd_to_iso_string(float $jd, int $calendar): string {}

/** @return string */
function celestial_jd_to_iso_string(float $jd, int $calendar): string {}

/** @return float[] */
function sign_ingress_ut(int $planet, float $jd, int $flags, bool $backward): array {}

/** @return float[] */
function celestial_sign_ingress_ut(int $planet, float $jd, int $flags, bool $backward): array {}

/** @return float */
function arabic_part(float $asc, float $body2, float $body1): float {}

/** @return float */
function celestial_arabic_part(float $asc, float $body2, float $body1): float {}

/** @return float */
function transit_to_degree(int $planet, float $target_lon, float $jd, int $flags, bool $backward): float {}

/** @return float */
function celestial_transit_to_degree(int $planet, float $target_lon, float $jd, int $flags, bool $backward): float {}

/** @return float */
function mc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_mc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function solar_return_jd(float $jd_natal, int $return_year, int $flags): float {}

/** @return float */
function celestial_solar_return_jd(float $jd_natal, int $return_year, int $flags): float {}

/** @return float */
function lunar_return_jd(float $jd_natal, float $jd_start, int $flags): float {}

/** @return float */
function celestial_lunar_return_jd(float $jd_natal, float $jd_start, int $flags): float {}

/** @return float */
function midpoint(float $lon1, float $lon2): float {}

/** @return float */
function celestial_midpoint(float $lon1, float $lon2): float {}

/** @return int */
function sign_ruler(int $sign): int {}

/** @return int */
function celestial_sign_ruler(int $sign): int {}

/** @return string */
function zodiac_sign_name(int $sign): string {}

/** @return string */
function celestial_zodiac_sign_name(int $sign): string {}

/** @return float[] */
function lon_to_sign(float $lon): array {}

/** @return float[] */
function celestial_lon_to_sign(float $lon): array {}

/** @return float */
function local_apparent_solar_time(float $jd_ut, float $geolon_deg): float {}

/** @return float */
function celestial_local_apparent_solar_time(float $jd_ut, float $geolon_deg): float {}

/** @return float[] */
function annual_profection(array $cusps, int $age): array {}

/** @return float[] */
function celestial_annual_profection(array $cusps, int $age): array {}

/** @return array */
function vimshottari_dasha(float $jd_birth, float $moon_lon_sidereal, float $years_ahead): array {}

/** @return array */
function celestial_vimshottari_dasha(float $jd_birth, float $moon_lon_sidereal, float $years_ahead): array {}

/** @return array<string,mixed>|null */
function omer_from_jd(float $jd): ?array {}

/** @return array<string,mixed>|null */
function celestial_omer_from_jd(float $jd): ?array {}

/** @return float|null */
function omer_day_jd(int $hebrew_year, int $day): ?float {}

/** @return float|null */
function celestial_omer_day_jd(int $hebrew_year, int $day): ?float {}

/** @return float */
function omer_start_jd(int $hebrew_year): float {}

/** @return float */
function celestial_omer_start_jd(int $hebrew_year): float {}

/** @return array */
function omer_days(int $hebrew_year): array {}

/** @return array */
function celestial_omer_days(int $hebrew_year): array {}

/** @return string */
function omer_declaration(int $day): string {}

/** @return string */
function celestial_omer_declaration(int $day): string {}

/** @return array<string,mixed> */
function omer_period(float $jd): array {}

/** @return array<string,mixed> */
function celestial_omer_period(float $jd): array {}

/** @return array */
function jewish_holidays(int $hebrew_year): array {}

/** @return array */
function celestial_jewish_holidays(int $hebrew_year): array {}

/** @return float|null */
function jewish_holiday_jd(int $hebrew_year, string $name): ?float {}

/** @return float|null */
function celestial_jewish_holiday_jd(int $hebrew_year, string $name): ?float {}

/** @return int */
function hebrew_year_from_jd(float $jd): int {}

/** @return int */
function celestial_hebrew_year_from_jd(float $jd): int {}

/** @return array<string,mixed> */
function jd_to_hebrew_date(float $jd): array {}

/** @return array<string,mixed> */
function celestial_jd_to_hebrew_date(float $jd): array {}

/** @return array<string,mixed> */
function easter_gregorian(int $year): array {}

/** @return array<string,mixed> */
function celestial_easter_gregorian(int $year): array {}

/** @return array<string,mixed> */
function easter_orthodox(int $year): array {}

/** @return array<string,mixed> */
function celestial_easter_orthodox(int $year): array {}

/** @return float */
function easter_jd(int $year): float {}

/** @return float */
function celestial_easter_jd(int $year): float {}

/** @return float */
function easter_orthodox_jd(int $year): float {}

/** @return float */
function celestial_easter_orthodox_jd(int $year): float {}

/** @return array */
function christian_feasts(int $year): array {}

/** @return array */
function celestial_christian_feasts(int $year): array {}

/** @return array */
function christian_fixed_feasts(int $year): array {}

/** @return array */
function celestial_christian_fixed_feasts(int $year): array {}

/** @return array<string,mixed> */
function hijri_from_jd(float $jd): array {}

/** @return array<string,mixed> */
function celestial_hijri_from_jd(float $jd): array {}

/** @return float */
function hijri_to_jd(int $year, int $month, int $day): float {}

/** @return float */
function celestial_hijri_to_jd(int $year, int $month, int $day): float {}

/** @return string */
function hijri_month_name(int $month): string {}

/** @return string */
function celestial_hijri_month_name(int $month): string {}

/** @return int */
function days_in_hebrew_year(int $year): int {}

/** @return int */
function celestial_days_in_hebrew_year(int $year): int {}

/** @return int */
function months_in_hebrew_year(int $year): int {}

/** @return int */
function celestial_months_in_hebrew_year(int $year): int {}

/** @return bool */
function is_hebrew_leap_year(int $year): bool {}

/** @return bool */
function celestial_is_hebrew_leap_year(int $year): bool {}

/** @return int */
function hebrew_month_days(int $year, int $month): int {}

/** @return int */
function celestial_hebrew_month_days(int $year, int $month): int {}

/** @return int */
function hebrew_month_start_jd(int $year, int $month): int {}

/** @return int */
function celestial_hebrew_month_start_jd(int $year, int $month): int {}

/** @return int */
function hebrew_new_year_jd(int $year): int {}

/** @return int */
function celestial_hebrew_new_year_jd(int $year): int {}

/** @return bool */
function is_hijri_leap_year(int $year): bool {}

/** @return bool */
function celestial_is_hijri_leap_year(int $year): bool {}

/** @return int */
function hijri_month_days(int $year, int $month): int {}

/** @return int */
function celestial_hijri_month_days(int $year, int $month): int {}

/** @return float */
function hijri_month_start_jd(int $year, int $month): float {}

/** @return float */
function celestial_hijri_month_start_jd(int $year, int $month): float {}

/** @return float */
function hijri_new_year_jd(int $year): float {}

/** @return float */
function celestial_hijri_new_year_jd(int $year): float {}

/** @return bool */
function is_bahai_leap_year(int $bahai_year): bool {}

/** @return bool */
function celestial_is_bahai_leap_year(int $bahai_year): bool {}

/** @return array */
function islamic_observances(int $hijri_year): array {}

/** @return array */
function celestial_islamic_observances(int $hijri_year): array {}

/** @return array<string,mixed> */
function panchanga(float $jd): array {}

/** @return array<string,mixed> */
function celestial_panchanga(float $jd): array {}

/** @return array */
function hindu_festivals(int $gregorian_year): array {}

/** @return array */
function celestial_hindu_festivals(int $gregorian_year): array {}

/** @return float */
function vesak_jd(int $year): float {}

/** @return float */
function celestial_vesak_jd(int $year): float {}

/** @return array */
function uposatha_days(int $year): array {}

/** @return array */
function celestial_uposatha_days(int $year): array {}

/** @return float */
function nowruz_jd(int $year): float {}

/** @return float */
function celestial_nowruz_jd(int $year): float {}

/** @return int */
function gregorian_to_solar_hijri(int $year): int {}

/** @return int */
function celestial_gregorian_to_solar_hijri(int $year): int {}

/** @return float */
function naw_ruz_jd(int $bahai_year): float {}

/** @return float */
function celestial_naw_ruz_jd(int $bahai_year): float {}

/** @return array<string,mixed> */
function jd_to_bahai(float $jd): array {}

/** @return array<string,mixed> */
function celestial_jd_to_bahai(float $jd): array {}

/** @return array */
function bahai_holy_days(int $bahai_year): array {}

/** @return array */
function celestial_bahai_holy_days(int $bahai_year): array {}

/** @return string */
function moon_phase(float $jd): string {}

/** @return string */
function celestial_moon_phase(float $jd): string {}

/** @return float */
function moon_illumination(float $jd): float {}

/** @return float */
function celestial_moon_illumination(float $jd): float {}

/** @return float */
function moon_elongation(float $jd): float {}

/** @return float */
function celestial_moon_elongation(float $jd): float {}

/** @return float */
function moon_phase_angle(float $jd): float {}

/** @return float */
function celestial_moon_phase_angle(float $jd): float {}

/** @return float */
function next_new_moon(float $jd_from): float {}

/** @return float */
function celestial_next_new_moon(float $jd_from): float {}

/** @return float */
function next_first_quarter(float $jd_from): float {}

/** @return float */
function celestial_next_first_quarter(float $jd_from): float {}

/** @return float */
function next_full_moon_phase(float $jd_from): float {}

/** @return float */
function celestial_next_full_moon_phase(float $jd_from): float {}

/** @return float */
function next_last_quarter(float $jd_from): float {}

/** @return float */
function celestial_next_last_quarter(float $jd_from): float {}

/** @return array */
function moon_phases_for_month(int $year, int $month): array {}

/** @return array */
function celestial_moon_phases_for_month(int $year, int $month): array {}

/** @return array<string,mixed> */
function moon_phase_info(float $jd): array {}

/** @return array<string,mixed> */
function celestial_moon_phase_info(float $jd): array {}

/** @return bool */
function is_day_chart(float $sun_lon, array $cusps): bool {}

/** @return bool */
function celestial_is_day_chart(float $sun_lon, array $cusps): bool {}

/** @return int[] */
function almuten(float $lon, bool $is_day): array {}

/** @return int[] */
function celestial_almuten(float $lon, bool $is_day): array {}

/** @return int */
function decan_ruler(float $lon): int {}

/** @return int */
function celestial_decan_ruler(float $lon): int {}

/** @return int */
function egyptian_terms_ruler(float $lon): int {}

/** @return int */
function celestial_egyptian_terms_ruler(float $lon): int {}

/** @return int[] */
function triplicity_rulers(float $lon): array {}

/** @return int[] */
function celestial_triplicity_rulers(float $lon): array {}

/** @return array */
function firdaria(float $jd_birth, bool $is_day, float $span_years): array {}

/** @return array */
function celestial_firdaria(float $jd_birth, bool $is_day, float $span_years): array {}

/** @return float[] */
function solar_term_position(float $sun_lon): array {}

/** @return float[] */
function celestial_solar_term_position(float $sun_lon): array {}

/** @return string[] */
function sexagenary_name(int $cycle_index): array {}

/** @return string[] */
function celestial_sexagenary_name(int $cycle_index): array {}

/** @return string[] */
function medicine_wheel_totem(float $sun_lon): array {}

/** @return string[] */
function celestial_medicine_wheel_totem(float $sun_lon): array {}

/** @return array<string,mixed> */
function secondary_progressions(float $jd_natal, float $years, array $bodies, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return array<string,mixed> */
function celestial_secondary_progressions(float $jd_natal, float $years, array $bodies, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return float[] */
function solar_arc_directions(float $jd_natal, float $years, array $natal_positions, float $natal_mc, int $flags): array {}

/** @return float[] */
function celestial_solar_arc_directions(float $jd_natal, float $years, array $natal_positions, float $natal_mc, int $flags): array {}

/** @return array */
function midpoint_table(array $positions, float $orb): array {}

/** @return array */
function celestial_midpoint_table(array $positions, float $orb): array {}

/** @return array */
function calc_chart_aspects(array $positions, array $aspects, float $orb): array {}

/** @return array */
function celestial_calc_chart_aspects(array $positions, array $aspects, float $orb): array {}

/** @return array */
function calc_chart_aspects_auto(array $positions, array $aspects): array {}

/** @return array */
function celestial_calc_chart_aspects_auto(array $positions, array $aspects): array {}

/** @return float[] */
function monthly_profection(array $cusps, int $age_years, int $age_months): array {}

/** @return float[] */
function celestial_monthly_profection(array $cusps, int $age_years, int $age_months): array {}

/** @return array */
function next_esbat(float $jd_from): array {}

/** @return array */
function celestial_next_esbat(float $jd_from): array {}

/** @return float[]|null */
function next_aspect_cusp(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_cusp(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float */
function ic_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_ic_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function asc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_asc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function dsc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return float */
function celestial_dsc_transit_ut(int $planet, float $jd_natal, float $jd_start, float $lat, float $lon, int $hsys, int $flags, bool $backward): float {}

/** @return string[] */
function four_pillars(float $jd_ut, float $hour_ut, float $sun_lon): array {}

/** @return string[] */
function celestial_four_pillars(float $jd_ut, float $hour_ut, float $sun_lon): array {}

/** @return float[] */
function antiscion(array $pos, float $axis): array {}

/** @return float[] */
function celestial_antiscion(array $pos, float $axis): array {}

/** @return float */
function ayanamsa(float $jd_et): float {}

/** @return float */
function celestial_ayanamsa(float $jd_et): float {}

/** @return float */
function ayanamsa_ut(float $jd_ut): float {}

/** @return float */
function celestial_ayanamsa_ut(float $jd_ut): float {}

/** @return string */
function ayanamsa_name(int $sid_mode): string {}

/** @return string */
function celestial_ayanamsa_name(int $sid_mode): string {}

/** @return string[] */
function calendar_round(float $jd): array {}

/** @return string[] */
function celestial_calendar_round(float $jd): array {}

/** @return int[] */
function degsplit(float $pos): array {}

/** @return int[] */
function celestial_degsplit(float $pos): array {}

/** @return string[] */
function egyptian_decan(float $lon): array {}

/** @return string[] */
function celestial_egyptian_decan(float $lon): array {}

/** @return string[]|null */
function solar_cycle(float $jd): ?array {}

/** @return string[]|null */
function celestial_solar_cycle(float $jd): ?array {}

/** @return string|null */
function grand_solar_epoch(float $jd): ?string {}

/** @return string|null */
function celestial_grand_solar_epoch(float $jd): ?string {}

/** @return string|null */
function cycle_nickname(int $n): ?string {}

/** @return string|null */
function celestial_cycle_nickname(int $n): ?string {}

/** @return float[] */
function fixstar2(string $star, float $tjdet, int $flags): array {}

/** @return float[] */
function celestial_fixstar2(string $star, float $tjdet, int $flags): array {}

/** @return float */
function fixstar2_mag(string $star): float {}

/** @return float */
function celestial_fixstar2_mag(string $star): float {}

/** @return float[] */
function fixstar2_ut(string $star, float $tjdut, int $flags): array {}

/** @return float[] */
function celestial_fixstar2_ut(string $star, float $tjdut, int $flags): array {}

/** @return float[] */
function fixstar_ut(string $star, float $tjdut, int $flags): array {}

/** @return float[] */
function celestial_fixstar_ut(string $star, float $tjdut, int $flags): array {}

/** @return string[] */
function full_dignity(int $body, float $lon, bool $is_day): array {}

/** @return string[] */
function celestial_full_dignity(int $body, float $lon, bool $is_day): array {}

/** @return int[] */
function gregorian_to_hijri_years(int $gregorian_year): array {}

/** @return int[] */
function celestial_gregorian_to_hijri_years(int $gregorian_year): array {}

/** @return string[] */
function haab(float $jd): array {}

/** @return string[] */
function celestial_haab(float $jd): array {}

/** @return string */
function house_name_str(int $hsys): string {}

/** @return string */
function celestial_house_name_str(int $hsys): string {}

/** @return float[] */
function houses_ex2(float $tjdut, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return float[] */
function celestial_houses_ex2(float $tjdut, float $lat, float $lon, int $hsys, int $flags): array {}

/** @return int[] */
function jd_duration(float $jd_start, float $jd_end): array {}

/** @return int[] */
function celestial_jd_duration(float $jd_start, float $jd_end): array {}

/** @return float[] */
function lun_eclipse_how(float $jd_ut, ?array $geopos, int $flags): array {}

/** @return float[] */
function celestial_lun_eclipse_how(float $jd_ut, ?array $geopos, int $flags): array {}

/** @return float[] */
function lun_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function celestial_lun_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function match_aspect2(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return float[] */
function celestial_match_aspect2(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $orb): array {}

/** @return float[] */
function match_aspect3(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb, float $def_orb): array {}

/** @return float[] */
function celestial_match_aspect3(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb, float $def_orb): array {}

/** @return float[] */
function match_aspect4(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb, float $def_orb): array {}

/** @return float[] */
function celestial_match_aspect4(float $pos0, float $speed0, float $pos1, float $speed1, float $aspect, float $app_orb, float $sep_orb, float $def_orb): array {}

/** @return float */
function mean_sidtime(float $jd): float {}

/** @return float */
function celestial_mean_sidtime(float $jd): float {}

/** @return float[] */
function mooncross_node(float $jd_et, int $flags): array {}

/** @return float[] */
function celestial_mooncross_node(float $jd_et, int $flags): array {}

/** @return float[] */
function mooncross_node_ut(float $jd_ut, int $flags): array {}

/** @return float[] */
function celestial_mooncross_node_ut(float $jd_ut, int $flags): array {}

/** @return int */
function naisargika_relation(int $gr1, int $gr2): int {}

/** @return int */
function celestial_naisargika_relation(int $gr1, int $gr2): int {}

/** @return float[]|null */
function next_aspect(int $planet, float $aspect, float $fixed_pt, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect(int $planet, float $aspect, float $fixed_pt, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function next_aspect_cusp2(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_cusp2(int $body, float $aspect, int $cusp, float $jd_start, float $lat, float $lon, int $hsys, bool $backward, int $flags): ?array {}

/** @return float[]|null */
function next_aspect_with(int $planet, float $aspect, int $other, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_with(int $planet, float $aspect, int $other, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return array */
function next_sabbat(float $jd_from): array {}

/** @return array */
function celestial_next_sabbat(float $jd_from): array {}

/** @return float */
function ochchabala(int $graha, float $sputha): float {}

/** @return float */
function celestial_ochchabala(int $graha, float $sputha): float {}

/** @return int[]|null */
function parse_datetime(string $s): ?array {}

/** @return int[]|null */
function celestial_parse_datetime(string $s): ?array {}

/** @return string */
function planet_name(int $planet): string {}

/** @return string */
function celestial_planet_name(int $planet): string {}

/** @return float[] */
function refrac_extended(float $altitude, float $geoalt, float $pressure_mb, float $temp_c, float $lapse_rate, int $calc_flag): array {}

/** @return float[] */
function celestial_refrac_extended(float $altitude, float $geoalt, float $pressure_mb, float $temp_c, float $lapse_rate, int $calc_flag): array {}

/** @return float */
function residential_strength(float $graha, array $bm): float {}

/** @return float */
function celestial_residential_strength(float $graha, array $bm): float {}

/** @return float[] */
function retrograde_station_ut(int $planet, float $jd, int $flags): array {}

/** @return float[] */
function celestial_retrograde_station_ut(int $planet, float $jd, int $flags): array {}

/** @return int[] */
function revjul_hms(float $jd, int $calendar): array {}

/** @return int[] */
function celestial_revjul_hms(float $jd, int $calendar): array {}

/** @return float[] */
function saturn_4_stars(float $jd, int $flags): array {}

/** @return float[] */
function celestial_saturn_4_stars(float $jd, int $flags): array {}

/** @return void */
function set_jpl_file(string $fname): void {}

/** @return void */
function celestial_set_jpl_file(string $fname): void {}

/** @return int */
function sign_ruler_modern(int $sign): int {}

/** @return int */
function celestial_sign_ruler_modern(int $sign): int {}

/** @return float[] */
function sol_eclipse_how(float $jd_ut, array $geopos, int $flags): array {}

/** @return float[] */
function celestial_sol_eclipse_how(float $jd_ut, array $geopos, int $flags): array {}

/** @return float[] */
function sol_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function celestial_sol_eclipse_when_loc(float $tjd_start, array $geopos, int $flags, bool $backwards): array {}

/** @return float[] */
function sol_eclipse_where(float $tjd, int $flags): array {}

/** @return float[] */
function celestial_sol_eclipse_where(float $tjd, int $flags): array {}

/** @return string[] */
function tonalpohualli(float $jd): array {}

/** @return string[] */
function celestial_tonalpohualli(float $jd): array {}

/** @return string[] */
function tzolkin(float $jd): array {}

/** @return string[] */
function celestial_tzolkin(float $jd): array {}

/** @return float[] */
function utc_to_jd(int $year, int $month, int $day, int $hour, int $minute, float $second, int $calendar): array {}

/** @return float[] */
function celestial_utc_to_jd(int $year, int $month, int $day, int $hour, int $minute, float $second, int $calendar): array {}

/** @return string[] */
function xiuhpohualli(float $jd): array {}

/** @return string[] */
function celestial_xiuhpohualli(float $jd): array {}

/** @return float */
function degnorm(float $d): float {}

/** @return float */
function celestial_degnorm(float $d): float {}

/** @return float */
function difdeg2n(float $p1, float $p2): float {}

/** @return float */
function celestial_difdeg2n(float $p1, float $p2): float {}

/** @return float */
function get_ayanamsa(float $jd_et): float {}

/** @return float */
function celestial_get_ayanamsa(float $jd_et): float {}

/** @return string */
function get_ayanamsa_name(int $sid_mode): string {}

/** @return string */
function celestial_get_ayanamsa_name(int $sid_mode): string {}

/** @return string */
function next_sabbat_name(float $jd_from): string {}

/** @return string */
function celestial_next_sabbat_name(float $jd_from): string {}

/** @return float */
function next_full_moon(float $jd_start): float {}

/** @return float */
function celestial_next_full_moon(float $jd_start): float {}

/** @return float */
function solcross_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float */
function celestial_solcross_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return int[] */
function iso_week(float $jd): array {}

/** @return int[] */
function celestial_iso_week(float $jd): array {}

/** @return int */
function day_of_year(int $year, int $month, int $day): int {}

/** @return int */
function celestial_day_of_year(int $year, int $month, int $day): int {}

/** @return int */
function weeks_in_iso_year(int $year): int {}

/** @return int */
function celestial_weeks_in_iso_year(int $year): int {}

/** @return int[] */
function maya_long_count(float $jd): array {}

/** @return int[] */
function celestial_maya_long_count(float $jd): array {}

/** @return string */
function maya_long_count_str(float $jd): string {}

/** @return string */
function celestial_maya_long_count_str(float $jd): string {}

/** @return float[] */
function yallop_q(float $arcv_deg, float $arcl_deg, float $sd_arcmin): array {}

/** @return float[] */
function celestial_yallop_q(float $arcv_deg, float $arcl_deg, float $sd_arcmin): array {}

/** @return float */
function best_time_method(float $jd_sunset, float $jd_moonset): float {}

/** @return float */
function celestial_best_time_method(float $jd_sunset, float $jd_moonset): float {}

/** @return float|null */
function vietnamese_month_start_jd(float $jd_ut): ?float {}

/** @return float|null */
function celestial_vietnamese_month_start_jd(float $jd_ut): ?float {}

/** @return bool */
function vietnamese_chinese_boundary_differs(float $jd_ut): bool {}

/** @return bool */
function celestial_vietnamese_chinese_boundary_differs(float $jd_ut): bool {}

/** @return float */
function coptic_to_jd(int $year, int $month, int $day): float {}

/** @return float */
function celestial_coptic_to_jd(int $year, int $month, int $day): float {}

/** @return int[] */
function jd_to_coptic(float $jd): array {}

/** @return int[] */
function celestial_jd_to_coptic(float $jd): array {}

/** @return float */
function ethiopic_to_jd(int $year, int $month, int $day): float {}

/** @return float */
function celestial_ethiopic_to_jd(int $year, int $month, int $day): float {}

/** @return int[] */
function jd_to_ethiopic(float $jd): array {}

/** @return int[] */
function celestial_jd_to_ethiopic(float $jd): array {}

/** @return bool */
function is_coptic_leap_year(int $year): bool {}

/** @return bool */
function celestial_is_coptic_leap_year(int $year): bool {}

/** @return int */
function coptic_month_days(int $year, int $month): int {}

/** @return int */
function celestial_coptic_month_days(int $year, int $month): int {}

/** @return float|null */
function fasli_nowruz_jd(int $year): ?float {}

/** @return float|null */
function celestial_fasli_nowruz_jd(int $year): ?float {}

/** @return int[]|null */
function jd_to_fasli(float $jd): ?array {}

/** @return int[]|null */
function celestial_jd_to_fasli(float $jd): ?array {}

/** @return float|null */
function losar_jd(int $year): ?float {}

/** @return float|null */
function celestial_losar_jd(int $year): ?float {}

/** @return string[] */
function tibetan_year_name(int $year): array {}

/** @return string[] */
function celestial_tibetan_year_name(int $year): array {}

/** @return int */
function approx_hebrew_year(float $jd): int {}

/** @return int */
function celestial_approx_hebrew_year(float $jd): int {}

/** @return array */
function arabic_parts_seven(float $asc, float $sun, float $moon, float $sat, float $mar, float $jup, float $mer, float $ven, bool $is_day): array {}

/** @return array */
function celestial_arabic_parts_seven(float $asc, float $sun, float $moon, float $sat, float $mar, float $jup, float $mer, float $ven, bool $is_day): array {}

/** @return float */
function diff_deg(float $p1, float $p2): float {}

/** @return float */
function celestial_diff_deg(float $p1, float $p2): float {}

/** @return float */
function distance_to_mc(float $planet_lon, float $mc_lon): float {}

/** @return float */
function celestial_distance_to_mc(float $planet_lon, float $mc_lon): float {}

/** @return int[] */
function easter_julian(int $year): array {}

/** @return int[] */
function celestial_easter_julian(int $year): array {}

/** @return int */
function elapsed_days(int $year): int {}

/** @return int */
function celestial_elapsed_days(int $year): int {}

/** @return int[] */
function geo_to_dms(float $coord): array {}

/** @return int[] */
function celestial_geo_to_dms(float $coord): array {}

/** @return float[] */
function heliacal_ut(float $jd_start, array $dgeo, array $datm, array $dobs, string $objectname, int $type_event, int $flags): array {}

/** @return float[] */
function celestial_heliacal_ut(float $jd_start, array $dgeo, array $datm, array $dobs, string $objectname, int $type_event, int $flags): array {}

/** @return float */
function helio_cross(int $body, float $x2cross, float $jd_et, int $flags, int $dir): float {}

/** @return float */
function celestial_helio_cross(int $body, float $x2cross, float $jd_et, int $flags, int $dir): float {}

/** @return float */
function helio_cross_ut(int $body, float $x2cross, float $jd_ut, int $flags, int $dir): float {}

/** @return float */
function celestial_helio_cross_ut(int $body, float $x2cross, float $jd_ut, int $flags, int $dir): float {}

/** @return int|null */
function house_system_char(int $id): ?int {}

/** @return int|null */
function celestial_house_system_char(int $id): ?int {}

/** @return int|null */
function house_system_id(int $hsys): ?int {}

/** @return int|null */
function celestial_house_system_id(int $hsys): ?int {}

/** @return float[] */
function houses_armc(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return float[] */
function celestial_houses_armc(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return float[] */
function houses_armc_ex2(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return float[] */
function celestial_houses_armc_ex2(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return float[] */
function houses_from_armc(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return float[] */
function celestial_houses_from_armc(float $armc, float $lat, float $eps, int $hsys): array {}

/** @return array */
function islamic_observances_for_jd(float $jd): array {}

/** @return array */
function celestial_islamic_observances_for_jd(float $jd): array {}

/** @return float[] */
function jd_et_to_utc(float $jd_et, int $calendar): array {}

/** @return float[] */
function celestial_jd_et_to_utc(float $jd_et, int $calendar): array {}

/** @return float[] */
function jd_ut_to_utc(float $jd_ut, int $calendar): array {}

/** @return float[] */
function celestial_jd_ut_to_utc(float $jd_ut, int $calendar): array {}

/** @return string */
function karana_name(int $karana): string {}

/** @return string */
function celestial_karana_name(int $karana): string {}

/** @return float */
function lat_to_lmt(float $tjd_lat, float $geolon): float {}

/** @return float */
function celestial_lat_to_lmt(float $tjd_lat, float $geolon): float {}

/** @return float */
function lmt_to_lat(float $tjd_lmt, float $geolon): float {}

/** @return float */
function celestial_lmt_to_lat(float $tjd_lmt, float $geolon): float {}

/** @return array<string,mixed> */
function lower_meridian_transit_ut(int $body, float $jd_start, array $geopos, int $flags): array {}

/** @return array<string,mixed> */
function celestial_lower_meridian_transit_ut(int $body, float $jd_start, array $geopos, int $flags): array {}

/** @return array<string,mixed> */
function lun_occult_when_glob(float $tjd_start, int $body, string $starname, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function celestial_lun_occult_when_glob(float $tjd_start, int $body, string $starname, int $flags, int $ecl_type, bool $backwards): array {}

/** @return array<string,mixed> */
function lun_occult_when_loc(float $tjd_start, int $body, string $starname, int $flags, array $geopos, bool $backwards): array {}

/** @return array<string,mixed> */
function celestial_lun_occult_when_loc(float $tjd_start, int $body, string $starname, int $flags, array $geopos, bool $backwards): array {}

/** @return array<string,mixed> */
function lun_occult_where(float $jd_ut, int $body, string $starname, int $flags): array {}

/** @return array<string,mixed> */
function celestial_lun_occult_where(float $jd_ut, int $body, string $starname, int $flags): array {}

/** @return float */
function mean_sidereal_time_deg(float $jd_ut): float {}

/** @return float */
function celestial_mean_sidereal_time_deg(float $jd_ut): float {}

/** @return array<string,mixed> */
function meridian_transit_ut(int $body, float $jd_start, array $geopos, int $flags): array {}

/** @return array<string,mixed> */
function celestial_meridian_transit_ut(int $body, float $jd_start, array $geopos, int $flags): array {}

/** @return float */
function mooncross(float $x2cross, float $jd_et, int $flags): float {}

/** @return float */
function celestial_mooncross(float $x2cross, float $jd_et, int $flags): float {}

/** @return float */
function mooncross_back_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float */
function celestial_mooncross_back_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float */
function mooncross_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float */
function celestial_mooncross_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float[]|null */
function next_aspect2(int $planet, float $aspect, float $fixed_pt, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect2(int $planet, float $aspect, float $fixed_pt, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function next_aspect_with2(int $planet, float $aspect, int $other, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float[]|null */
function celestial_next_aspect_with2(int $planet, float $aspect, int $other, float $jd_start, bool $backward, float $stop_days, int $flags): ?array {}

/** @return float */
function next_full_moon_after(float $jd_start): float {}

/** @return float */
function celestial_next_full_moon_after(float $jd_start): float {}

/** @return float */
function next_new_moon_after(float $jd_start): float {}

/** @return float */
function celestial_next_new_moon_after(float $jd_start): float {}

/** @return string[] */
function next_principal_phase(float $jd_from, int $phase): array {}

/** @return string[] */
function celestial_next_principal_phase(float $jd_from, int $phase): array {}

/** @return float[] */
function nod_aps(float $jd_et, int $body, int $flags, int $method): array {}

/** @return float[] */
function celestial_nod_aps(float $jd_et, int $body, int $flags, int $method): array {}

/** @return float[] */
function nod_aps_ut(float $jd_ut, int $body, int $flags, int $method): array {}

/** @return float[] */
function celestial_nod_aps_ut(float $jd_ut, int $body, int $flags, int $method): array {}

/** @return float */
function parallactic_angle(float $ha_deg, float $dec_deg, float $lat_deg): float {}

/** @return float */
function celestial_parallactic_angle(float $ha_deg, float $dec_deg, float $lat_deg): float {}

/** @return int[]|null */
function parse_time(string $s): ?array {}

/** @return int[]|null */
function celestial_parse_time(string $s): ?array {}

/** @return float[] */
function pheno(float $jd_et, int $body, int $flags): array {}

/** @return float[] */
function celestial_pheno(float $jd_et, int $body, int $flags): array {}

/** @return float[] */
function pheno_ut(float $jd_ut, int $body, int $flags): array {}

/** @return float[] */
function celestial_pheno_ut(float $jd_ut, int $body, int $flags): array {}

/** @return bool */
function planet_conjunct_mc(float $planet_lon, float $mc_lon, float $orb): bool {}

/** @return bool */
function celestial_planet_conjunct_mc(float $planet_lon, float $mc_lon, float $orb): bool {}

/** @return int */
function planet_house_number(float $planet_lon, array $cusps): int {}

/** @return int */
function celestial_planet_house_number(float $planet_lon, array $cusps): int {}

/** @return float|null */
function planet_on_midpoint(float $planet_lon, float $mid_lon, float $orb): ?float {}

/** @return float|null */
function celestial_planet_on_midpoint(float $planet_lon, float $mid_lon, float $orb): ?float {}

/** @return int */
function rasi_diff(int $r1, int $r2): int {}

/** @return int */
function celestial_rasi_diff(int $r1, int $r2): int {}

/** @return int */
function rasi_diff2(int $r1, int $r2): int {}

/** @return int */
function celestial_rasi_diff2(int $r1, int $r2): int {}

/** @return int */
function rasi_norm(int $r): int {}

/** @return int */
function celestial_rasi_norm(int $r): int {}

/** @return array<string,mixed> */
function rise_trans_true_hor(float $tjdut, int $planet, int $flags, int $event_type, array $geopos, float $pressure_mb, float $temp_c, float $horhgt): array {}

/** @return array<string,mixed> */
function celestial_rise_trans_true_hor(float $tjdut, int $planet, int $flags, int $event_type, array $geopos, float $pressure_mb, float $temp_c, float $horhgt): array {}

/** @return bool */
function same_sect(int $body, bool $is_day): bool {}

/** @return bool */
function celestial_same_sect(int $body, bool $is_day): bool {}

/** @return int|null */
function sidereal_mode_flag(int $sidmode): ?int {}

/** @return int|null */
function celestial_sidereal_mode_flag(int $sidmode): ?int {}

/** @return int|null */
function sidereal_mode_id(int $flag): ?int {}

/** @return int|null */
function celestial_sidereal_mode_id(int $flag): ?int {}

/** @return float */
function sidereal_time_deg(float $jd_ut): float {}

/** @return float */
function celestial_sidereal_time_deg(float $jd_ut): float {}

/** @return float */
function sidtime0(float $jd_ut, float $eps, float $nut): float {}

/** @return float */
function celestial_sidtime0(float $jd_ut, float $eps, float $nut): float {}

/** @return int */
function sign_exaltation(int $body): int {}

/** @return int */
function celestial_sign_exaltation(int $body): int {}

/** @return int|null */
function sign_lord(int $sign): ?int {}

/** @return int|null */
function celestial_sign_lord(int $sign): ?int {}

/** @return int */
function solar_hijri_to_gregorian(int $solar_hijri_year): int {}

/** @return int */
function celestial_solar_hijri_to_gregorian(int $solar_hijri_year): int {}

/** @return float */
function solcross(float $x2cross, float $jd_et, int $flags): float {}

/** @return float */
function celestial_solcross(float $x2cross, float $jd_et, int $flags): float {}

/** @return float */
function solcross_back_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return float */
function celestial_solcross_back_ut(float $x2cross, float $jd_ut, int $flags): float {}

/** @return int */
function tatkalika_relation(int $r1, int $r2): int {}

/** @return int */
function celestial_tatkalika_relation(int $r1, int $r2): int {}

/** @return float */
function time_equ(float $jd_ut): float {}

/** @return float */
function celestial_time_equ(float $jd_ut): float {}

/** @return float */
function tt_to_ut(float $jde): float {}

/** @return float */
function celestial_tt_to_ut(float $jde): float {}

/** @return array */
function tz_abbr_find(string $abbr): array {}

/** @return array */
function celestial_tz_abbr_find(string $abbr): array {}

/** @return float[] */
function utc_time_zone(int $year, int $month, int $day, int $hour, int $minute, float $second, float $d_timezone): array {}

/** @return float[] */
function celestial_utc_time_zone(int $year, int $month, int $day, int $hour, int $minute, float $second, float $d_timezone): array {}

/** @return float */
function years_diff(float $jd1, float $jd2, int $flags): float {}

/** @return float */
function celestial_years_diff(float $jd1, float $jd2, int $flags): float {}
