// Auto-generated by `cargo xtask dts` — do not edit.
// Regenerate: cargo xtask dts

export interface PlanetPos {
  lon: number;
  lat: number;
  dist: number;
  speedLon: number;
  speedLat: number;
  speedDist: number;
  retFlags: number;
}

export interface StarPos {
  xx: Array<number>;
  starName: string;
  retFlags: number;
}

export interface HouseResult {
  cusps: Array<number>;
  ascmc: Array<number>;
}

export interface HouseResultEx2 {
  cusps: Array<number>;
  ascmc: Array<number>;
  cuspSpeeds: Array<number>;
  ascmcSpeeds: Array<number>;
}

export interface EclipseResult {
  retFlags: number;
  tret: Array<number>;
}

export interface EclipseResultAttr {
  retFlags: number;
  tret: Array<number>;
  attr: Array<number>;
}

export interface EclipseWhere {
  retFlags: number;
  geopos: Array<number>;
  attr: Array<number>;
}

export interface EclipseHow {
  retFlags: number;
  attr: Array<number>;
}

export interface RiseTrans {
  retFlags: number;
  tret: number;
}

export interface AzAlt {
  azimuth: number;
  trueAlt: number;
  apparentAlt: number;
}

export interface CalDate {
  year: number;
  month: number;
  day: number;
  hour: number;
}

export interface UtcDate {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
}

export interface JdPair {
  et: number;
  ut1: number;
}

export interface RefracExt {
  result: number;
  dret: Array<number>;
}

export interface ArabicPartResult {
  name: string;
  formula: string;
  degree: number;
}

export interface TzAbbrResult {
  name: string;
  desc: string;
  offset: string;
  hours: number;
  minutes: number;
}

export interface MoonCrossNodeResult {
  jdCross: number;
  xlon: number;
}

export interface IngressResult {
  jd: number;
  sign: number;
}

export interface SecondaryProgressionsResult {
  positions: Array<Array<number>>;
  cusps: Array<number>;
}

export interface Stations {
  retrograde: number;
  direct: number;
}

export interface OmerDay {
  day: number;
  week: number;
  dayOfWeek: number;
  weekSefirah: string;
  daySefirah: string;
  hebrewText: string;
  isLagBaomer: boolean;
  jd: number;
}

export interface OmerPeriod {
  startJd: number;
  endJd: number;
  hebrewYear: number;
}

export interface JewishHoliday {
  name: string;
  hebrewName: string;
  hebrewMonth: number;
  hebrewDay: number;
  jd: number;
  jdEnd: number;
  days: number;
  category: string;
}

export interface HebrewDate {
  year: number;
  month: number;
  day: number;
}

export interface CalendarDate {
  year: number;
  month: number;
  day: number;
}

export interface ChristianFeast {
  name: string;
  easterOffset: number;
  jd: number;
  year: number;
  month: number;
  day: number;
}

export interface HijriDate {
  year: number;
  month: number;
  day: number;
}

export interface IslamicObservance {
  name: string;
  arabicName: string;
  hijriMonth: number;
  hijriDay: number;
  jd: number;
  days: number;
}

export interface HijriYears {
  year1: number;
  year2: number;
}

export interface Panchanga {
  tithi: number;
  tithiName: string;
  paksha: string;
  vara: number;
  varaName: string;
  nakshatra: number;
  nakshatraName: string;
  nakshatraPada: number;
  yoga: number;
  yogaName: string;
  karana: number;
  karanaName: string;
  sunLon: number;
  moonLon: number;
  elongation: number;
}

export interface HinduFestival {
  name: string;
  description: string;
  jd: number;
}

export interface Uposatha {
  phase: string;
  jd: number;
  elongation: number;
}

export interface BahaiDate {
  year: number;
  month: number;
  day: number;
  monthName: string;
}

export interface BahaiHolyDay {
  name: string;
  description: string;
  bahaiMonth: number;
  bahaiDay: number;
  jd: number;
}

export interface PhaseEvent {
  phase: string;
  jd: number;
  elongation: number;
}

export interface MoonPhaseInfo {
  phaseName: string;
  elongation: number;
  illumination: number;
  prevPhaseName: string;
  prevPhaseJd: number;
  nextPhaseName: string;
  nextPhaseJd: number;
  ageDays: number;
}

export interface SolarCycleInfo {
  cycleNum: number;
  phase: number;
  phaseName: string;
  minJd: number;
  maxJd: number;
  nextMinJd: number;
  yearsSinceMin: number;
  nickname?: string | null;
  grandEpoch?: string | null;
}

export declare const GREG_CAL: number;
export declare const JUL_CAL: number;
export declare const SUN: number;
export declare const MOON: number;
export declare const MERCURY: number;
export declare const VENUS: number;
export declare const MARS: number;
export declare const JUPITER: number;
export declare const SATURN: number;
export declare const URANUS: number;
export declare const NEPTUNE: number;
export declare const PLUTO: number;
export declare const MEAN_NODE: number;
export declare const TRUE_NODE: number;
export declare const CHIRON: number;
export declare const FLG_BUILTIN: number;
export declare const FLG_SPEED: number;
export declare const EARTH: number;
export declare const FLG_JPL: number;
export declare const FLG_MOSHIER: number;
export declare const FLG_EQUATORIAL: number;
export declare const FLG_TOPOCTR: number;
export declare const FLG_SIDEREAL: number;
export declare const FLG_HELCTR: number;
export declare const FLG_XYZ: number;
export declare const FLG_RADIANS: number;
export declare const FLG_NONUT: number;
export declare const SIDM_FAGAN_BRADLEY: number;
export declare const SIDM_LAHIRI: number;
export declare const SIDM_RAMAN: number;
export declare const SIDM_USER: number;
export declare const ECL_TOTAL: number;
export declare const ECL_ANNULAR: number;
export declare const ECL_PARTIAL: number;
export declare const ECL_PENUMBRAL: number;
export declare const CALC_RISE: number;
export declare const CALC_SET: number;
export declare const TRUE_TO_APP: number;
export declare const APP_TO_TRUE: number;
export declare const SPLIT_DEG_ROUND_SEC: number;
export declare const SPLIT_DEG_ZODIACAL: number;
export declare const SPLIT_DEG_ROUND_MIN: number;
export declare const SPLIT_DEG_ROUND_DEG: number;
export declare const SPLIT_DEG_NAKSHATRA: number;
export declare const ECL_CENTRAL: number;
export declare const FLG_NOGDEFL: number;
export declare const FLG_NOABERR: number;
export declare const SIDM_KRISHNAMURTI: number;

export declare function setEphePath(path: string): void;
export declare function setJplFile(fname: string): void;
export declare function setSidMode(sidMode: number, t0?: number | null, ayanT0?: number | null): void;
export declare function setTopo(geolon: number, geolat: number, geoalt: number): void;
export declare function close(): void;
export declare function calc(tjdet: number, planet: number, flags: number): PlanetPos;
export declare function calcUt(tjdut: number, planet: number, flags: number): PlanetPos;
export declare function nutation(jde: number): Array<number>;
export declare function meanObliquity(jde: number): number;
export declare function trueObliquity(jde: number): number;
export declare function calcMany(tjdet: number, planets: Array<number>, flags: number): Array<PlanetPos>;
export declare function calcUtMany(tjdut: number, planets: Array<number>, flags: number): Array<PlanetPos>;
export declare function calcPctr(tjdet: number, planet: number, center: number, flags: number): PlanetPos;
export declare function fixstar(star: string, tjdet: number, flags: number): StarPos;
export declare function fixstarUt(star: string, tjdut: number, flags: number): StarPos;
export declare function fixstarMag(star: string): number;
export declare function houses(tjdut: number, lat: number, lon: number, hsys: number): HouseResult;
export declare function housesEx(tjdut: number, lat: number, lon: number, hsys: number, flags?: number | null): HouseResult;
export declare function housesEx2(tjdut: number, lat: number, lon: number, hsys: number, flags?: number | null): HouseResultEx2;
export declare function houseName(hsys: number): string;
export declare function solEclipseWhenGlob(tjdStart: number, flags: number, eclType?: number | null, backwards?: boolean | null): EclipseResult;
export declare function solEclipseWhenLoc(tjdStart: number, geopos: Array<number>, flags: number, backwards?: boolean | null): EclipseResultAttr;
export declare function solEclipseHow(jdUt: number, geopos: Array<number>, flags: number): EclipseHow;
export declare function solEclipseWhere(tjd: number, flags: number): EclipseWhere;
export declare function lunEclipseWhen(tjdStart: number, flags: number, eclType?: number | null, backwards?: boolean | null): EclipseResult;
export declare function lunEclipseHow(jdUt: number, geopos?: Array<number> | null, flags: number): EclipseHow;
export declare function riseTrans(tjdut: number, planet: number, epheFlags: number, eventType: number, geopos: Array<number>, pressureMb?: number | null, tempC?: number | null): RiseTrans;
export declare function julday(year: number, month: number, day: number, hour?: number | null, calendar?: number | null): number;
export declare function revjul(jd: number, calendar?: number | null): CalDate;
export declare function dayOfWeek(jd: number): number;
export declare function deltat(tjd: number): number;
export declare function sidtime(jdUt: number): number;
export declare function utcToJd(date: UtcDate, calendar?: number | null): JdPair;
export declare function ayanamsa(jdEt: number): number;
export declare function ayanamsaUt(jdUt: number): number;
export declare function ayanamsaName(sidMode: number): string;
export declare function degMidp(x1: number, x0: number): number;
export declare function splitDeg(deg: number, roundFlag: number): Array<number>;
export declare function coordTransform(coord: Array<number>, eps: number): Array<number>;
export declare function azalt(tjdut: number, calcFlag: number, geopos: Array<number>, pressureMb: number, tempC: number, xin: Array<number>): AzAlt;
export declare function refrac(altitude: number, pressureMb: number, tempC: number, calcFlag: number): number;
export declare function refracExtended(altitude: number, geoalt: number, pressureMb: number, tempC: number, lapseRate: number, calcFlag: number): RefracExt;
export declare function planetName(planet: number): string;
export declare function jdDuration(jdStart: number, jdEnd: number): Array<number>;
export declare function jdToIsoString(jd: number, calendar: number): string;
export declare function mooncrossNode(jdEt: number, flags: number): MoonCrossNodeResult;
export declare function mooncrossNodeUt(jdUt: number, flags: number): MoonCrossNodeResult;
export declare function setDeltaTUserdef(dt: number): void;
export declare function revjulHms(jd: number, calendar: number): Array<number>;
export declare function parseDatetime(s: string): Array<number> | null;
export declare function degsplit(pos: number): Array<number>;
export declare function antiscion(pos: Array<number>, axis: number): Array<number>;
export declare function matchAspect(pos0: number, speed0: number, pos1: number, speed1: number, aspect: number, orb: number): Array<number>;
export declare function matchAspect2(pos0: number, speed0: number, pos1: number, speed1: number, aspect: number, orb: number): Array<number>;
export declare function matchAspect3(pos0: number, speed0: number, pos1: number, speed1: number, aspect: number, appOrb: number, sepOrb: number, defOrb: number): Array<number>;
export declare function matchAspect4(pos0: number, speed0: number, pos1: number, speed1: number, aspect: number, appOrb: number, sepOrb: number, defOrb: number): Array<number>;
export declare function nextRetro(planet: number, jdStart: number, backward: boolean, stopDays: number, flags: number): Array<number> | null;
export declare function nextAspect(planet: number, aspect: number, fixedPt: number, jdStart: number, backward: boolean, stopDays: number, flags: number): Array<number> | null;
export declare function nextAspectWith(planet: number, aspect: number, other: number, jdStart: number, backward: boolean, stopDays: number, flags: number): Array<number> | null;
export declare function housePos(armc: number, lat: number, eps: number, hsys: number, lon: number, latBody: number): number;
export declare function lunEclipseWhenLoc(tjdStart: number, geopos: Array<number>, flags: number, backwards: boolean): EclipseResultAttr;
export declare function fixstar2(star: string, tjdet: number, flags: number): StarPos;
export declare function fixstar2Ut(star: string, tjdut: number, flags: number): StarPos;
export declare function fixstar2Mag(star: string): number;
export declare function azaltRev(tjdut: number, calcFlag: number, geopos: Array<number>, az: number, alt: number): Array<number>;
export declare function signName(sign: number): string | null;
export declare function jdnow(): number;
export declare function parseCoord(s: string): number | null;
export declare function formatCoord(coord: number, isLatitude: boolean): string | null;
export declare function longToRasi(lon: number): number;
export declare function longToNavamsa(lon: number): number;
export declare function longToNakshatra(lon: number): Array<number>;
export declare function nakshatraName(nak: number): string | null;
export declare function ramanHouses(asc: number, mc: number, sandhi: boolean): Array<number>;
export declare function residentialStrength(graha: number, bm: Array<number>): number;
export declare function ochchabala(graha: number, sputha: number): number;
export declare function naisargakaRelation(gr1: number, gr2: number): number;
export declare function saturnFourStars(jd: number, flags: number): Array<number>;
export declare function version(): string;
export declare function normDeg(x: number): number;
export declare function diffDegSigned(p1: number, p2: number): number;
export declare function normCs(p: number): number;
export declare function signIngressUt(planet: number, jd: number, flags: number, backward: boolean): IngressResult;
export declare function retrogradeStationUt(planet: number, jd: number, flags: number): Stations;
export declare function arabicPart(asc: number, body2: number, body1: number): number;
export declare function transitToDegree(planet: number, targetLon: number, jd: number, flags: number, backward: boolean): number;
export declare function mcTransitUt(planet: number, jdNatal: number, jdStart: number, lat: number, lon: number, hsys: number, flags: number, backward: boolean): number;
export declare function solarReturnJd(jdNatal: number, returnYear: number, flags: number): number;
export declare function lunarReturnJd(jdNatal: number, jdStart: number, flags: number): number;
export declare function midpoint(lon1: number, lon2: number): number;
export declare function signRuler(sign: number): number;
export declare function signRulerModern(sign: number): number;
export declare function zodiacSignName(sign: number): string;
export declare function lonToSign(lon: number): Array<number>;
export declare function localApparentSolarTime(jdUt: number, geolonDeg: number): number;
export declare function annualProfection(cusps: Array<number>, age: number): Array<number>;
export declare function vimshottariDasha(jdBirth: number, moonLonSidereal: number, yearsAhead: number): Array<Array<number>>;
export declare function omerFromJd(jd: number): OmerDay | null;
export declare function omerDayJd(hebrewYear: number, day: number): number | null;
export declare function omerStartJd(hebrewYear: number): number;
export declare function omerDays(hebrewYear: number): Array<OmerDay>;
export declare function omerPeriod(jd: number): OmerPeriod;
export declare function omerDeclaration(day: number): string;
export declare function jewishHolidays(hebrewYear: number): Array<JewishHoliday>;
export declare function jewishHolidayJd(hebrewYear: number, name: string): number | null;
export declare function hebrewYearFromJd(jd: number): number;
export declare function jdToHebrewDate(jd: number): HebrewDate;
export declare function easterGregorian(year: number): CalendarDate;
export declare function easterOrthodox(year: number): CalendarDate;
export declare function easterJd(year: number): number;
export declare function easterOrthodoxJd(year: number): number;
export declare function christianFeasts(year: number): Array<ChristianFeast>;
export declare function christianFixedFeasts(year: number): Array<ChristianFeast>;
export declare function hijriFromJd(jd: number): HijriDate;
export declare function hijriToJd(year: number, month: number, day: number): number;
export declare function hijriMonthName(month: number): string;
export declare function daysInHebrewYear(year: number): number;
export declare function monthsInHebrewYear(year: number): number;
export declare function isHebrewLeapYear(year: number): boolean;
export declare function hebrewMonthDays(year: number, month: number): number;
export declare function hebrewMonthStartJd(year: number, month: number): number;
export declare function hebrewNewYearJd(year: number): number;
export declare function isHijriLeapYear(year: number): boolean;
export declare function hijriMonthDays(year: number, month: number): number;
export declare function hijriMonthStartJd(year: number, month: number): number;
export declare function hijriNewYearJd(year: number): number;
export declare function isBahaiLeapYear(bahaiYear: number): boolean;
export declare function islamicObservances(hijriYear: number): Array<IslamicObservance>;
export declare function gregorianToHijriYears(gregorianYear: number): HijriYears;
export declare function panchanga(jd: number): Panchanga;
export declare function hinduFestivals(gregorianYear: number): Array<HinduFestival>;
export declare function vesakJd(year: number): number;
export declare function uposathaDays(year: number): Array<Uposatha>;
export declare function nowruzJd(year: number): number;
export declare function gregorianToSolarHijri(year: number): number;
export declare function nawRuzJd(bahaiYear: number): number;
export declare function jdToBahai(jd: number): BahaiDate;
export declare function bahaiHolyDays(bahaiYear: number): Array<BahaiHolyDay>;
export declare function moonPhase(jd: number): string;
export declare function moonIllumination(jd: number): number;
export declare function moonElongation(jd: number): number;
export declare function moonPhaseAngle(jd: number): number;
export declare function nextNewMoon(jdFrom: number): number;
export declare function nextFirstQuarter(jdFrom: number): number;
export declare function nextFullMoonPhase(jdFrom: number): number;
export declare function nextLastQuarter(jdFrom: number): number;
export declare function moonPhasesForMonth(year: number, month: number): Array<PhaseEvent>;
export declare function moonPhaseInfo(jd: number): MoonPhaseInfo;
export declare function egyptianTermsRuler(lon: number): number;
export declare function decanRuler(lon: number): number;
export declare function fullDignity(bodyRaw: number, lon: number, isDay: boolean): Array<unknown>;
export declare function almuten(lon: number, isDay: boolean): Array<number>;
export declare function firdaria(jdBirth: number, isDay: boolean, spanYears: number): Array<Array<number>>;
export declare function fourPillars(jdUt: number, hourUt: number, sunLon: number): Array<Array<string>>;
export declare function solarTermPosition(sunLon: number): Array<number>;
export declare function tonalpohualli(jd: number): Array<string>;
export declare function xiuhpohualli(jd: number): Array<string>;
export declare function tzolkin(jd: number): Array<string>;
export declare function haab(jd: number): Array<string>;
export declare function calendarRound(jd: number): Array<string>;
export declare function medicineWheelTotem(sunLon: number): Array<string>;
export declare function egyptianDecan(lon: number): Array<string>;
export declare function solarCycle(jd: number): SolarCycleInfo | null;
export declare function grandSolarEpoch(jd: number): string | null;
export declare function cycleNickname(n: number): string | null;
export declare function isDayChart(sunLon: number, cusps: Array<number>): boolean;
export declare function meanSidtime(jd: number): number;
export declare function triplicityRulers(lon: number): Array<number>;
export declare function sabbatsForYear(year: number): Array<Array<number>>;
export declare function sabbatJd(year: number, kind: string): number;
export declare function nextSabbat(jdFrom: number): Array<unknown>;
export declare function esbatsForYear(year: number): Array<number>;
export declare function nextEsbat(jdFrom: number): Array<unknown>;
export declare function secondaryProgressions(jdNatal: number, years: number, bodies: Array<number>, lat: number, lon: number, hsys: number, flags: number): SecondaryProgressionsResult;
export declare function solarArcDirections(jdNatal: number, years: number, natalPositions: Array<number>, natalMc: number, flags: number): Array<number>;
export declare function midpointTable(positions: Array<number>, orb: number): Array<Array<number>>;
export declare function calcChartAspects(positions: Array<number>, aspects: Array<number>, orb: number): Array<Array<number>>;
export declare function calcChartAspectsAuto(positions: Array<number>, aspects: Array<number>): Array<Array<number>>;
export declare function sexagenaryName(cycleIndex: number): Array<string>;
export declare function monthlyProfection(cusps: Array<number>, ageYears: number, ageMonths: number): Array<number>;
export declare function icTransitUt(planet: number, jdNatal: number, jdStart: number, lat: number, lon: number, hsys: number, flags: number, backward: boolean): number;
export declare function ascTransitUt(planet: number, jdNatal: number, jdStart: number, lat: number, lon: number, hsys: number, flags: number, backward: boolean): number;
export declare function dscTransitUt(planet: number, jdNatal: number, jdStart: number, lat: number, lon: number, hsys: number, flags: number, backward: boolean): number;
export declare function nextAspectCusp(body: number, aspect: number, cusp: number, jdStart: number, lat: number, lon: number, hsys: number, backward: boolean, flags: number): Array<number> | null;
export declare function nextAspectCusp2(body: number, aspect: number, cusp: number, jdStart: number, lat: number, lon: number, hsys: number, backward: boolean, flags: number): Array<number> | null;
export declare function degnorm(d: number): number;
export declare function difdeg2n(p1: number, p2: number): number;
export declare function nextFullMoon(jdStart: number): number;
export declare function nextSabbatName(jdFrom: number): string;
export declare function solcrossUt(x2cross: number, jdUt: number, flags: number): number;
export declare function isoWeek(jd: number): Array<number>;
export declare function dayOfYear(year: number, month: number, day: number): number;
export declare function weeksInIsoYear(year: number): number;
export declare function mayaLongCount(jd: number): Array<number>;
export declare function mayaLongCountStr(jd: number): string;
export declare function yallopQ(arcvDeg: number, arclDeg: number, sdArcmin: number): Array<number>;
export declare function bestTimeMethod(jdSunset: number, jdMoonset: number): number;
export declare function vietnameseMonthStartJd(jdUt: number): number | null;
export declare function vietnameseChineseBoundaryDiffers(jdUt: number): boolean;
export declare function copticToJd(year: number, month: number, day: number): number;
export declare function jdToCoptic(jd: number): Array<number>;
export declare function ethiopicToJd(year: number, month: number, day: number): number;
export declare function jdToEthiopic(jd: number): Array<number>;
export declare function isCopticLeapYear(year: number): boolean;
export declare function copticMonthDays(year: number, month: number): number;
export declare function fasliNowruzJd(year: number): number | null;
export declare function jdToFasli(jd: number): Array<number> | null;
export declare function losarJd(year: number): number | null;
export declare function tibetanYearName(year: number): Array<string>;
export declare function approxHebrewYear(jd: number): number;
export declare function arabicPartsSeven(asc: number, sun: number, moon: number, sat: number, mar: number, jup: number, mer: number, ven: number, isDay: boolean): Array<ArabicPartResult>;
export declare function diffDeg(p1: number, p2: number): number;
export declare function distanceToMc(planetLon: number, mcLon: number): number;
export declare function easterJulian(year: number): Array<number>;
export declare function elapsedDays(year: number): number;
export declare function geoToDms(coord: number): Array<number>;
export declare function heliacalUt(jdStart: number, dgeo: Array<number>, datm: Array<number>, dobs: Array<number>, objectname: string, typeEvent: number, flags: number): Array<number>;
export declare function helioCross(body: number, x2cross: number, jdEt: number, flags: number, dir: number): number;
export declare function helioCrossUt(body: number, x2cross: number, jdUt: number, flags: number, dir: number): number;
export declare function houseSystemChar(id: number): number | null;
export declare function houseSystemId(hsys: number): number | null;
export declare function housesArmc(armc: number, lat: number, eps: number, hsys: number): HouseResult;
export declare function housesArmcEx2(armc: number, lat: number, eps: number, hsys: number): HouseResultEx2;
export declare function housesFromArmc(armc: number, lat: number, eps: number, hsys: number): HouseResult;
export declare function islamicObservancesForJd(jd: number): Array<IslamicObservance>;
export declare function jdEtToUtc(jdEt: number, calendar: number): Array<number>;
export declare function jdUtToUtc(jdUt: number, calendar: number): Array<number>;
export declare function karanaName(karana: number): string;
export declare function latToLmt(tjdLat: number, geolon: number): number;
export declare function lmtToLat(tjdLmt: number, geolon: number): number;
export declare function lowerMeridianTransitUt(body: number, jdStart: number, geopos: Array<number>, flags: number): RiseTrans;
export declare function lunOccultWhenGlob(tjdStart: number, body: number, starname: string, flags: number, eclType: number, backwards: boolean): EclipseResult;
export declare function lunOccultWhenLoc(tjdStart: number, body: number, starname: string, flags: number, geopos: Array<number>, backwards: boolean): EclipseResultAttr;
export declare function lunOccultWhere(jdUt: number, body: number, starname: string, flags: number): EclipseWhere;
export declare function meanSiderealTimeDeg(jdUt: number): number;
export declare function meridianTransitUt(body: number, jdStart: number, geopos: Array<number>, flags: number): RiseTrans;
export declare function mooncross(x2cross: number, jdEt: number, flags: number): number;
export declare function mooncrossBackUt(x2cross: number, jdUt: number, flags: number): number;
export declare function mooncrossUt(x2cross: number, jdUt: number, flags: number): number;
export declare function nextAspect2(planet: number, aspect: number, fixedPt: number, jdStart: number, backward: boolean, stopDays: number, flags: number): Array<number> | null;
export declare function nextAspectWith2(planet: number, aspect: number, other: number, jdStart: number, backward: boolean, stopDays: number, flags: number): Array<number> | null;
export declare function nextFullMoonAfter(jdStart: number): number;
export declare function nextNewMoonAfter(jdStart: number): number;
export declare function nextPrincipalPhase(jdFrom: number, phase: number): PhaseEvent;
export declare function nodAps(jdEt: number, body: number, flags: number, method: number): Array<number>;
export declare function nodApsUt(jdUt: number, body: number, flags: number, method: number): Array<number>;
export declare function parallacticAngle(haDeg: number, decDeg: number, latDeg: number): number;
export declare function parseTime(s: string): Array<number> | null;
export declare function pheno(jdEt: number, body: number, flags: number): Array<number>;
export declare function phenoUt(jdUt: number, body: number, flags: number): Array<number>;
export declare function planetConjunctMc(planetLon: number, mcLon: number, orb: number): boolean;
export declare function planetHouseNumber(planetLon: number, cusps: Array<number>): number;
export declare function planetOnMidpoint(planetLon: number, midLon: number, orb: number): number | null;
export declare function rasiDiff(r1: number, r2: number): number;
export declare function rasiDiff2(r1: number, r2: number): number;
export declare function rasiNorm(r: number): number;
export declare function riseTransTrueHor(tjdut: number, planet: number, flags: number, eventType: number, geopos: Array<number>, pressureMb: number, tempC: number, horhgt: number): RiseTrans;
export declare function sameSect(body: number, isDay: boolean): boolean;
export declare function siderealModeFlag(sidmode: number): number | null;
export declare function siderealModeId(flag: number): number | null;
export declare function siderealTimeDeg(jdUt: number): number;
export declare function sidtime0(jdUt: number, eps: number, nut: number): number;
export declare function signExaltation(body: number): number;
export declare function signLord(sign: number): number | null;
export declare function solarHijriToGregorian(solarHijriYear: number): number;
export declare function solcross(x2cross: number, jdEt: number, flags: number): number;
export declare function solcrossBackUt(x2cross: number, jdUt: number, flags: number): number;
export declare function tatkalikaRelation(r1: number, r2: number): number;
export declare function timeEqu(jdUt: number): number;
export declare function ttToUt(jde: number): number;
export declare function tzAbbrFind(abbr: string): Array<TzAbbrResult>;
export declare function utcTimeZone(year: number, month: number, day: number, hour: number, minute: number, second: number, dTimezone: number): Array<number>;
export declare function yearsDiff(jd1: number, jd2: number, flags: number): number;
