"""
celestial_py — type stubs for the PyO3 extension module.

Generated from bindings/python/src/lib.rs.
All functions are available via:  import celestial_py as celestial
"""

from __future__ import annotations
from typing import Any

# ── Body constants ─────────────────────────────────────────────────────────────
SUN: int
MOON: int
MERCURY: int
VENUS: int
MARS: int
JUPITER: int
SATURN: int
URANUS: int
NEPTUNE: int
PLUTO: int
MEAN_NODE: int
TRUE_NODE: int
CHIRON: int

# ── Calculation flags ──────────────────────────────────────────────────────────
FLG_BUILTIN: int
FLG_SPEED: int
FLG_SIDEREAL: int
FLG_EQUATORIAL: int
FLG_HELCTR: int
FLG_TOPOCTR: int
FLG_NONUT: int
FLG_RADIANS: int
FLG_XYZ: int
SEFLG_SPEED: int

# ── Sidereal modes ─────────────────────────────────────────────────────────────
SIDM_LAHIRI: int
SIDM_FAGAN_BRADLEY: int
SIDM_DELUCE: int
SIDM_RAMAN: int
SIDM_KRISHNAMURTI: int
SIDM_SASSANIAN: int
SIDM_USER: int

# ── Calendar constants ─────────────────────────────────────────────────────────
GREG_CAL: int
JUL_CAL: int
SE_GREG_CAL: int

# ── Rise/set event types ───────────────────────────────────────────────────────
CALC_RISE: int
CALC_SET: int
CALC_MTRANSIT: int
CALC_ITRANSIT: int

# ── Aspect constants ───────────────────────────────────────────────────────────
SYNODIC_MONTH: float
GMT_CORRELATION: int

# ── Dignity enum values ────────────────────────────────────────────────────────
DIGNITY_DOMICILE: str
DIGNITY_EXALTATION: str
DIGNITY_DETRIMENT: str
DIGNITY_FALL: str
DIGNITY_PEREGRINE: str

class PlanetPos:
    lon: float
    lat: float
    dist: float
    speed_lon: float
    speed_lat: float
    speed_dist: float
    ret_flags: int

class HouseResult:
    cusps: list[float]  # 13 elements, index 0 unused
    ascmc: list[float]  # 8 elements: ASC, MC, ARMC, Vertex, ...

class NutationResult:
    dpsi: float
    deps: float
    eps_true: float

class RiseTransResult:
    tret: float
    trise: float
    tset: float
    ttransit: float

class CalDate:
    year: int
    month: int
    day: int
    hour: float

class AspectMatch:
    matched: bool
    diff: float
    speed: float
    factor: float

class BaZiPillar:
    stem_name: str
    branch_name: str
    animal: str
    stem_element: str
    branch_element: str
    yang: bool

class FirdariaPeriod:
    major_lord: int
    minor_lord: int
    start: float
    end: float
    years: float

class JewishHoliday:
    name: str
    jd: float
    days: int

class MoonPhaseInfo:
    phase_name: str
    illumination: float
    elongation: float
    age_days: float
    prev_phase_name: str
    prev_phase_jd: float
    next_phase_name: str
    next_phase_jd: float

# ── All exported functions ─────────────────────────────────────────────────────
def set_jpl_file(fname: str) -> None: ...
def set_topo(geolon: float, geolat: float, geoalt: float) -> None: ...
def set_delta_t_userdef(dt: float) -> None: ...
def close() -> None: ...
def fixstar_mag(star: str) -> float: ...
def fixstar2_mag(star: str) -> float: ...
def house_name(hsys: int) -> str: ...
def revjul(py: Any, jd: float, calendar: int) -> Any: ...
def day_of_week(jd: float) -> int: ...
def deltat(tjd: float) -> float: ...
def sidtime(jd_ut: float) -> float: ...
def mean_sidtime(jd_ut: float) -> float: ...
def utc_to_jd(
    py: Any,
    year: int,
    month: int,
    day: int,
    hour: int,
    minute: int,
    second: float,
    calendar: int,
) -> Any: ...
def ayanamsa(jd_et: float) -> float: ...
def ayanamsa_ut(jd_ut: float) -> float: ...
def ayanamsa_name(sid_mode: int) -> Any: ...
def norm_deg(x: float) -> float: ...
def midpoint_deg(x1: float, x0: float) -> float: ...
def diff_deg_signed(p1: float, p2: float) -> float: ...
def norm_cs(p: int) -> int: ...
def split_deg(py: Any, deg: float, round_flag: int) -> Any: ...
def coord_transform(py: Any, coord: Any, eps: float) -> Any: ...
def azalt(
    py: Any,
    tjdut: float,
    calc_flag: int,
    geopos: Any,
    pressure_mb: float,
    temp_c: float,
    xin: Any,
) -> Any: ...
def azalt_rev(
    py: Any, tjdut: float, calc_flag: int, geopos: Any, az: float, alt: float
) -> Any: ...
def refrac(
    altitude: float, pressure_mb: float, temp_c: float, calc_flag: int
) -> float: ...
def refrac_extended(
    py: Any,
    altitude: float,
    geoalt: float,
    pressure_mb: float,
    temp_c: float,
    lapse_rate: float,
    calc_flag: int,
) -> Any: ...
def version() -> str: ...
def planet_name(planet: int) -> Any: ...
def match_aspect4(
    py: Any,
    pos0: float,
    speed0: float,
    pos1: float,
    speed1: float,
    aspect: float,
    app_orb: float,
    sep_orb: float,
    def_orb: float,
) -> Any: ...
def antiscion(py: Any, pos: Any, axis: float) -> Any: ...
def jdnow() -> float: ...
def revjul_hms(py: Any, jd: float, calendar: int) -> Any: ...
def parse_datetime(py: Any, s: str) -> Any: ...
def jd_duration(py: Any, jd_start: float, jd_end: float) -> Any: ...
def jd_to_iso_string(jd: float, calendar: int) -> str: ...
def degsplit(py: Any, pos: float) -> Any: ...
def sign_name(sign: int) -> Any | None: ...
def parse_coord(s: str) -> float | None: ...
def format_coord(coord: float, is_latitude: bool) -> str | None: ...
def long_to_rasi(lon: float) -> int: ...
def long_to_navamsa(lon: float) -> int: ...
def long_to_nakshatra(py: Any, lon: float) -> Any: ...
def nakshatra_name(n: int) -> Any | None: ...
def raman_houses(py: Any, asc: float, mc: float, sandhi: bool) -> Any: ...
def naisargika_relation(gr1: int, gr2: int) -> int | None: ...
def ochchabala(graha: int, sputha: float) -> float | None: ...
def residential_strength(py: Any, graha: float, bm: Any) -> Any: ...
def saturn_4_stars(py: Any, jd: float, flags: int) -> Any: ...
def arabic_part(asc: float, body2: float, body1: float) -> float: ...
def solar_return_jd(jd_natal: float, return_year: int, flags: int) -> float: ...
def lunar_return_jd(jd_natal: float, jd_start: float, flags: int) -> float: ...
def midpoint(lon1: float, lon2: float) -> float: ...
def sign_ruler(sign: int) -> int: ...
def sign_ruler_modern(sign: int) -> int: ...
def zodiac_sign_name(sign: int) -> Any: ...
def lon_to_sign(lon: float) -> Any: ...
def local_apparent_solar_time(jd_ut: float, geolon_deg: float) -> float: ...
def annual_profection(py: Any, cusps: list[float], age: int) -> Any: ...
def omer_from_jd(py: Any, jd: float) -> Any: ...
def omer_day_jd(hebrew_year: int, day: int) -> float | None: ...
def omer_start_jd(hebrew_year: int) -> float: ...
def omer_days(py: Any, hebrew_year: int) -> Any: ...
def omer_period(py: Any, jd: float) -> Any: ...
def omer_declaration(day: int) -> str: ...
def egyptian_terms_ruler(lon: float) -> int: ...
def decan_ruler(lon: float) -> int: ...
def triplicity_rulers(py: Any, lon: float) -> Any: ...
def full_dignity(py: Any, body_raw: int, lon: float, is_day: bool) -> Any: ...
def almuten(py: Any, lon: float, is_day: bool) -> Any: ...
def is_day_chart(sun_lon: float, cusps: list[float]) -> bool: ...
def firdaria(py: Any, jd_birth: float, is_day: bool, span_years: float) -> Any: ...
def four_pillars(py: Any, jd_ut: float, hour_ut: float, sun_lon: float) -> Any: ...
def solar_term_position(py: Any, sun_lon: float) -> Any: ...
def tonalpohualli(py: Any, jd: float) -> Any: ...
def xiuhpohualli(py: Any, jd: float) -> Any: ...
def tzolkin(py: Any, jd: float) -> Any: ...
def haab(py: Any, jd: float) -> Any: ...
def calendar_round(py: Any, jd: float) -> Any: ...
def medicine_wheel_totem(py: Any, sun_lon: float) -> Any: ...
def egyptian_decan(py: Any, lon: float) -> Any: ...
def moon_phase(jd: float) -> str: ...
def moon_illumination(jd: float) -> float: ...
def moon_elongation(jd: float) -> float: ...
def moon_phase_angle(jd: float) -> float: ...
def next_new_moon(jd_from: float) -> float: ...
def next_first_quarter(jd_from: float) -> float: ...
def next_full_moon_phase(jd_from: float) -> float: ...
def next_last_quarter(jd_from: float) -> float: ...
def moon_phases_for_month(py: Any, year: int, month: int) -> Any: ...
def moon_phase_info(py: Any, jd: float) -> Any: ...
def jewish_holidays(py: Any, hebrew_year: int) -> Any: ...
def jewish_holiday_jd(hebrew_year: int, name: str) -> float | None: ...
def hebrew_year_from_jd(jd: float) -> int: ...
def jd_to_hebrew_date(py: Any, jd: float) -> Any: ...
def easter_gregorian(py: Any, year: int) -> Any: ...
def easter_orthodox(py: Any, year: int) -> Any: ...
def easter_jd(year: int) -> float: ...
def easter_orthodox_jd(year: int) -> float: ...
def christian_feasts(py: Any, year: int) -> Any: ...
def christian_fixed_feasts(py: Any, year: int) -> Any: ...
def hijri_from_jd(py: Any, jd: float) -> Any: ...
def hijri_to_jd(year: int, month: int, day: int) -> float: ...
def hijri_month_name(month: int) -> Any: ...
def islamic_observances(py: Any, hijri_year: int) -> Any: ...
def gregorian_to_hijri_years(py: Any, gregorian_year: int) -> Any: ...
def panchanga(py: Any, jd: float) -> Any: ...
def hindu_festivals(py: Any, gregorian_year: int) -> Any: ...
def vesak_jd(year: int) -> float: ...
def uposatha_days(py: Any, year: int) -> Any: ...
def nowruz_jd(year: int) -> float: ...
def gregorian_to_solar_hijri(year: int) -> int: ...
def naw_ruz_jd(bahai_year: int) -> float: ...
def jd_to_bahai(py: Any, jd: float) -> Any: ...
def bahai_holy_days(py: Any, bahai_year: int) -> Any: ...

# ── Sabbats & Esbats ────────────────────────────────────────────────────────────────
def sabbats_for_year(year: int) -> list[list]: ...
def next_sabbat(jd_from: float) -> tuple[str, float]: ...
def sabbat_jd(year: int, kind: int) -> float: ...
def esbats_for_year(year: int) -> list[list]: ...
def next_esbat(jd_from: float) -> tuple[str, float]: ...

# ── Angle transits ──────────────────────────────────────────────────────────────────
def ic_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                  hsys: int, flags: int, backward: bool) -> float: ...
def asc_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                   hsys: int, flags: int, backward: bool) -> float: ...
def dsc_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                   hsys: int, flags: int, backward: bool) -> float: ...
def next_aspect_cusp(body: int, aspect: float, cusp: int, jd_start: float,
                     lat: float, lon: float, hsys: int, backward: bool,
                     flags: int) -> tuple[float, float] | None: ...

# ── Chart analysis ──────────────────────────────────────────────────────────────────
def secondary_progressions(jd_natal: float, years: float, bodies: list[int],
                            lat: float, lon: float, hsys: int,
                            flags: int) -> tuple[list, list[float]]: ...
def solar_arc_directions(jd_natal: float, years: float,
                          natal_positions: list[tuple[int, float]],
                          natal_mc: float, flags: int) -> tuple[float, list, float]: ...
def midpoint_table(positions: list[tuple[int, float]], orb: float) -> list[tuple[int, int, float]]: ...
def calc_chart_aspects(positions: list[tuple[int, float, float]],
                        aspects: list[float], orb: float) -> list[tuple]: ...
def calc_chart_aspects_auto(positions: list[tuple[int, float, float]]) -> list[tuple]: ...

# ── Sexagenary / monthly profection ────────────────────────────────────────────────
def sexagenary_name(cycle_index: int) -> tuple[str, str]: ...
def monthly_profection(cusps: list[float], age_years: int, age_months: int) -> tuple[int, float]: ...

