"""
celestial_py — type stubs for the PyO3 extension module.

Generated from bindings/python/src/lib.rs.
All functions are available via:  import celestial_py as celestial
"""

from __future__ import annotations
from typing import Any

# ── Body constants ─────────────────────────────────────────────────────────────
SUN: int
MOON: int
MERCURY: int
VENUS: int
MARS: int
JUPITER: int
SATURN: int
URANUS: int
NEPTUNE: int
PLUTO: int
MEAN_NODE: int
TRUE_NODE: int
CHIRON: int

# ── Calculation flags ──────────────────────────────────────────────────────────
FLG_BUILTIN: int
FLG_SPEED: int
FLG_SIDEREAL: int
FLG_EQUATORIAL: int
FLG_HELCTR: int
FLG_TOPOCTR: int
FLG_NONUT: int
FLG_RADIANS: int
FLG_XYZ: int
SEFLG_SPEED: int

# ── Sidereal modes ─────────────────────────────────────────────────────────────
SIDM_LAHIRI: int
SIDM_FAGAN_BRADLEY: int
SIDM_DELUCE: int
SIDM_RAMAN: int
SIDM_KRISHNAMURTI: int
SIDM_SASSANIAN: int
SIDM_USER: int

# ── Calendar constants ─────────────────────────────────────────────────────────
GREG_CAL: int
JUL_CAL: int
SE_GREG_CAL: int

# ── Rise/set event types ───────────────────────────────────────────────────────
CALC_RISE: int
CALC_SET: int
CALC_MTRANSIT: int
CALC_ITRANSIT: int

# ── Aspect constants ───────────────────────────────────────────────────────────
SYNODIC_MONTH: float
GMT_CORRELATION: int

# ── Dignity enum values ────────────────────────────────────────────────────────
DIGNITY_DOMICILE: str
DIGNITY_EXALTATION: str
DIGNITY_DETRIMENT: str
DIGNITY_FALL: str
DIGNITY_PEREGRINE: str

class PlanetPos:
    lon: float
    lat: float
    dist: float
    speed_lon: float
    speed_lat: float
    speed_dist: float
    ret_flags: int

class HouseResult:
    cusps: list[float]  # 13 elements, index 0 unused
    ascmc: list[float]  # 8 elements: ASC, MC, ARMC, Vertex, ...

class NutationResult:
    dpsi: float
    deps: float
    eps_true: float

class RiseTransResult:
    tret: float
    trise: float
    tset: float
    ttransit: float

class CalDate:
    year: int
    month: int
    day: int
    hour: float

class AspectMatch:
    matched: bool
    diff: float
    speed: float
    factor: float

class BaZiPillar:
    stem_name: str
    branch_name: str
    animal: str
    stem_element: str
    branch_element: str
    yang: bool

class FirdariaPeriod:
    major_lord: int
    minor_lord: int
    start: float
    end: float
    years: float

class JewishHoliday:
    name: str
    jd: float
    days: int

class MoonPhaseInfo:
    phase_name: str
    illumination: float
    elongation: float
    age_days: float
    prev_phase_name: str
    prev_phase_jd: float
    next_phase_name: str
    next_phase_jd: float

# ── All exported functions ─────────────────────────────────────────────────────
def set_jpl_file(fname: str) -> None: ...
def set_topo(geolon: float, geolat: float, geoalt: float) -> None: ...
def set_delta_t_userdef(dt: float) -> None: ...
def close() -> None: ...
def fixstar_mag(star: str) -> float: ...
def fixstar2_mag(star: str) -> float: ...
def house_name(hsys: int) -> str: ...
def revjul(py: Any, jd: float, calendar: int) -> Any: ...
def day_of_week(jd: float) -> int: ...
def deltat(tjd: float) -> float: ...
def sidtime(jd_ut: float) -> float: ...
def mean_sidtime(jd_ut: float) -> float: ...
def utc_to_jd(
    py: Any,
    year: int,
    month: int,
    day: int,
    hour: int,
    minute: int,
    second: float,
    calendar: int,
) -> Any: ...
def ayanamsa(jd_et: float) -> float: ...
def ayanamsa_ut(jd_ut: float) -> float: ...
def ayanamsa_name(sid_mode: int) -> Any: ...
def norm_deg(x: float) -> float: ...
def midpoint_deg(x1: float, x0: float) -> float: ...
def diff_deg_signed(p1: float, p2: float) -> float: ...
def norm_cs(p: int) -> int: ...
def split_deg(py: Any, deg: float, round_flag: int) -> Any: ...
def coord_transform(py: Any, coord: Any, eps: float) -> Any: ...
def azalt(
    py: Any,
    tjdut: float,
    calc_flag: int,
    geopos: Any,
    pressure_mb: float,
    temp_c: float,
    xin: Any,
) -> Any: ...
def azalt_rev(
    py: Any, tjdut: float, calc_flag: int, geopos: Any, az: float, alt: float
) -> Any: ...
def refrac(
    altitude: float, pressure_mb: float, temp_c: float, calc_flag: int
) -> float: ...
def refrac_extended(
    py: Any,
    altitude: float,
    geoalt: float,
    pressure_mb: float,
    temp_c: float,
    lapse_rate: float,
    calc_flag: int,
) -> Any: ...
def version() -> str: ...
def planet_name(planet: int) -> Any: ...
def match_aspect4(
    py: Any,
    pos0: float,
    speed0: float,
    pos1: float,
    speed1: float,
    aspect: float,
    app_orb: float,
    sep_orb: float,
    def_orb: float,
) -> Any: ...
def antiscion(py: Any, pos: Any, axis: float) -> Any: ...
def jdnow() -> float: ...
def revjul_hms(py: Any, jd: float, calendar: int) -> Any: ...
def parse_datetime(py: Any, s: str) -> Any: ...
def jd_duration(py: Any, jd_start: float, jd_end: float) -> Any: ...
def jd_to_iso_string(jd: float, calendar: int) -> str: ...
def degsplit(py: Any, pos: float) -> Any: ...
def sign_name(sign: int) -> Any | None: ...
def parse_coord(s: str) -> float | None: ...
def format_coord(coord: float, is_latitude: bool) -> str | None: ...
def long_to_rasi(lon: float) -> int: ...
def long_to_navamsa(lon: float) -> int: ...
def long_to_nakshatra(py: Any, lon: float) -> Any: ...
def nakshatra_name(n: int) -> Any | None: ...
def raman_houses(py: Any, asc: float, mc: float, sandhi: bool) -> Any: ...
def naisargika_relation(gr1: int, gr2: int) -> int | None: ...
def ochchabala(graha: int, sputha: float) -> float | None: ...
def residential_strength(py: Any, graha: float, bm: Any) -> Any: ...
def saturn_4_stars(py: Any, jd: float, flags: int) -> Any: ...
def arabic_part(asc: float, body2: float, body1: float) -> float: ...
def solar_return_jd(jd_natal: float, return_year: int, flags: int) -> float: ...
def lunar_return_jd(jd_natal: float, jd_start: float, flags: int) -> float: ...
def midpoint(lon1: float, lon2: float) -> float: ...
def sign_ruler(sign: int) -> int: ...
def sign_ruler_modern(sign: int) -> int: ...
def zodiac_sign_name(sign: int) -> Any: ...
def lon_to_sign(lon: float) -> Any: ...
def local_apparent_solar_time(jd_ut: float, geolon_deg: float) -> float: ...
def annual_profection(py: Any, cusps: list[float], age: int) -> Any: ...
def omer_from_jd(py: Any, jd: float) -> Any: ...
def omer_day_jd(hebrew_year: int, day: int) -> float | None: ...
def omer_start_jd(hebrew_year: int) -> float: ...
def omer_days(py: Any, hebrew_year: int) -> Any: ...
def omer_period(py: Any, jd: float) -> Any: ...
def omer_declaration(day: int) -> str: ...
def egyptian_terms_ruler(lon: float) -> int: ...
def decan_ruler(lon: float) -> int: ...
def triplicity_rulers(py: Any, lon: float) -> Any: ...
def full_dignity(py: Any, body_raw: int, lon: float, is_day: bool) -> Any: ...
def almuten(py: Any, lon: float, is_day: bool) -> Any: ...
def is_day_chart(sun_lon: float, cusps: list[float]) -> bool: ...
def firdaria(py: Any, jd_birth: float, is_day: bool, span_years: float) -> Any: ...
def four_pillars(py: Any, jd_ut: float, hour_ut: float, sun_lon: float) -> Any: ...
def solar_term_position(py: Any, sun_lon: float) -> Any: ...
def tonalpohualli(py: Any, jd: float) -> Any: ...
def xiuhpohualli(py: Any, jd: float) -> Any: ...
def tzolkin(py: Any, jd: float) -> Any: ...
def haab(py: Any, jd: float) -> Any: ...
def calendar_round(py: Any, jd: float) -> Any: ...
def medicine_wheel_totem(py: Any, sun_lon: float) -> Any: ...
def egyptian_decan(py: Any, lon: float) -> Any: ...
def moon_phase(jd: float) -> str: ...
def moon_illumination(jd: float) -> float: ...
def moon_elongation(jd: float) -> float: ...
def moon_phase_angle(jd: float) -> float: ...
def next_new_moon(jd_from: float) -> float: ...
def next_first_quarter(jd_from: float) -> float: ...
def next_full_moon_phase(jd_from: float) -> float: ...
def next_last_quarter(jd_from: float) -> float: ...
def moon_phases_for_month(py: Any, year: int, month: int) -> Any: ...
def moon_phase_info(py: Any, jd: float) -> Any: ...
def jewish_holidays(py: Any, hebrew_year: int) -> Any: ...
def jewish_holiday_jd(hebrew_year: int, name: str) -> float | None: ...
def hebrew_year_from_jd(jd: float) -> int: ...
def jd_to_hebrew_date(py: Any, jd: float) -> Any: ...
def easter_gregorian(py: Any, year: int) -> Any: ...
def easter_orthodox(py: Any, year: int) -> Any: ...
def easter_jd(year: int) -> float: ...
def easter_orthodox_jd(year: int) -> float: ...
def christian_feasts(py: Any, year: int) -> Any: ...
def christian_fixed_feasts(py: Any, year: int) -> Any: ...
def hijri_from_jd(py: Any, jd: float) -> Any: ...
def hijri_to_jd(year: int, month: int, day: int) -> float: ...
def hijri_month_name(month: int) -> Any: ...
def islamic_observances(py: Any, hijri_year: int) -> Any: ...
def gregorian_to_hijri_years(py: Any, gregorian_year: int) -> Any: ...
def panchanga(py: Any, jd: float) -> Any: ...
def hindu_festivals(py: Any, gregorian_year: int) -> Any: ...
def vesak_jd(year: int) -> float: ...
def uposatha_days(py: Any, year: int) -> Any: ...
def nowruz_jd(year: int) -> float: ...
def gregorian_to_solar_hijri(year: int) -> int: ...
def naw_ruz_jd(bahai_year: int) -> float: ...
def jd_to_bahai(py: Any, jd: float) -> Any: ...
def bahai_holy_days(py: Any, bahai_year: int) -> Any: ...

# ── Sabbats & Esbats ────────────────────────────────────────────────────────────────
def sabbats_for_year(year: int) -> list[list]: ...
def next_sabbat(jd_from: float) -> tuple[str, float]: ...
def sabbat_jd(year: int, kind: int) -> float: ...
def esbats_for_year(year: int) -> list[list]: ...
def next_esbat(jd_from: float) -> tuple[str, float]: ...

# ── Angle transits ──────────────────────────────────────────────────────────────────
def ic_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                  hsys: int, flags: int, backward: bool) -> float: ...
def asc_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                   hsys: int, flags: int, backward: bool) -> float: ...
def dsc_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                   hsys: int, flags: int, backward: bool) -> float: ...
def next_aspect_cusp(body: int, aspect: float, cusp: int, jd_start: float,
                     lat: float, lon: float, hsys: int, backward: bool,
                     flags: int) -> tuple[float, float] | None: ...

# ── Chart analysis ──────────────────────────────────────────────────────────────────
def secondary_progressions(jd_natal: float, years: float, bodies: list[int],
                            lat: float, lon: float, hsys: int,
                            flags: int) -> tuple[list, list[float]]: ...
def solar_arc_directions(jd_natal: float, years: float,
                          natal_positions: list[tuple[int, float]],
                          natal_mc: float, flags: int) -> tuple[float, list, float]: ...
def midpoint_table(positions: list[tuple[int, float]], orb: float) -> list[tuple[int, int, float]]: ...
def calc_chart_aspects(positions: list[tuple[int, float, float]],
                        aspects: list[float], orb: float) -> list[tuple]: ...
def calc_chart_aspects_auto(positions: list[tuple[int, float, float]]) -> list[tuple]: ...

# ── Sexagenary / monthly profection ────────────────────────────────────────────────
def sexagenary_name(cycle_index: int) -> tuple[str, str]: ...
def monthly_profection(cusps: list[float], age_years: int, age_months: int) -> tuple[int, float]: ...

# ── Core calc / fixstar ─────────────────────────────────────────────────────────
def calc(tjdet: float, planet: int, flags: int) -> tuple[float, float, float, float, float, float]: ...
def calc_ut(tjdut: float, planet: int, flags: int) -> tuple[float, float, float, float, float, float]: ...
def calc_many(tjdet: float, planets: list[int], flags: int) -> list[tuple]: ...
def calc_ut_many(tjdut: float, planets: list[int], flags: int) -> list[tuple]: ...
def calc_pctr(tjdet: float, planet: int, center: int, flags: int) -> tuple[float, float, float, float, float, float]: ...
def fixstar(star: str, tjdet: float, flags: int) -> tuple[list[float], str]: ...
def fixstar_ut(star: str, tjdut: float, flags: int) -> tuple[list[float], str]: ...
def fixstar2(star: str, tjdet: float, flags: int) -> tuple[list[float], str]: ...
def fixstar2_ut(star: str, tjdut: float, flags: int) -> tuple[list[float], str]: ...
def julday(year: int, month: int, day: int, hour: float | None = None, calendar: int | None = None) -> float: ...

# ── Houses ──────────────────────────────────────────────────────────────────────
def houses(tjdut: float, lat: float, lon: float, hsys: int) -> tuple[list[float], list[float]]: ...
def houses_ex(tjdut: float, lat: float, lon: float, hsys: int, flags: int) -> tuple[list[float], list[float]]: ...
def houses_ex2(tjdut: float, lat: float, lon: float, hsys: int, flags: int) -> tuple[list[float], list[float], list[float], list[float]]: ...
def house_pos(armc: float, lat: float, eps: float, hsys: int, xx: list[float]) -> float: ...
def house_name_str(hsys: int) -> str: ...

# ── Obliquity / nutation ────────────────────────────────────────────────────────
def mean_obliquity(jde: float) -> float: ...
def true_obliquity(jde: float) -> float: ...
def nutation(jde: float) -> tuple[float, float]: ...

# ── Rise / transit / set ────────────────────────────────────────────────────────
def rise_trans(tjdut: float, planet: int, event_type: int, geopos: list[float],
               pressure_mb: float, temp_c: float, flags: int) -> tuple[int, list[float]]: ...

# ── Aspect matching ─────────────────────────────────────────────────────────────
def match_aspect(pos0: float, speed0: float, pos1: float, speed1: float,
                 aspect: float, orb: float) -> tuple[bool, float, float, float]: ...
def match_aspect2(pos0: float, speed0: float, pos1: float, speed1: float,
                  aspect: float, orb: float) -> tuple[bool, float, float, float]: ...
def match_aspect3(pos0: float, speed0: float, pos1: float, speed1: float,
                  aspect: float, app_orb: float, sep_orb: float) -> tuple[bool, float, float, float]: ...

# ── Angle transits / searches ───────────────────────────────────────────────────
def mc_transit_ut(body: int, jd_natal: float, jd_start: float, lat: float, lon: float,
                  hsys: int, flags: int, backward: bool) -> float: ...
def sign_ingress_ut(planet: int, jd: float, flags: int, backward: bool) -> float: ...
def transit_to_degree(planet: int, target_lon: float, jd_start: float,
                      flags: int, backward: bool) -> float: ...
def next_aspect(planet: int, aspect: float, fixed_pt: float, jd_start: float,
                backward: bool, stop_days: float, flags: int) -> tuple | None: ...
def next_aspect_with(planet: int, aspect: float, other: int, jd_start: float,
                     backward: bool, stop_days: float, flags: int) -> float | None: ...
def next_aspect_cusp2(body: int, aspect: float, cusp: int, jd_start: float,
                      lat: float, lon: float, hsys: int, backward: bool, flags: int) -> float | None: ...
def next_retro(planet: int, jd_start: float, backward: bool,
               stop_days: float, flags: int) -> tuple | None: ...
def retrograde_station_ut(planet: int, jd: float, flags: int) -> tuple[float, float]: ...

# ── Moon crossings ──────────────────────────────────────────────────────────────
def mooncross_node(jd_et: float, flags: int) -> tuple[float, float]: ...
def mooncross_node_ut(jd_ut: float, flags: int) -> tuple[float, float]: ...

# ── Eclipses ────────────────────────────────────────────────────────────────────
def lun_eclipse_how(jd_ut: float, flags: int, geopos: list[float] | None = None) -> tuple[int, list[float]]: ...
def lun_eclipse_when(tjd_start: float, flags: int, ecl_type: int, backwards: bool) -> tuple[int, list[float]]: ...
def lun_eclipse_when_loc(tjd_start: float, geopos: list[float], flags: int, backwards: bool) -> tuple[int, list[float]]: ...
def sol_eclipse_how(jd_ut: float, geopos: list[float], flags: int) -> tuple[int, list[float]]: ...
def sol_eclipse_when_glob(tjd_start: float, flags: int, ecl_type: int, backwards: bool) -> tuple[int, list[float]]: ...
def sol_eclipse_when_loc(tjd_start: float, geopos: list[float], flags: int, backwards: bool) -> tuple[int, list[float]]: ...
def sol_eclipse_where(tjd: float, flags: int) -> tuple[int, list[float], list[float]]: ...

# ── Sidereal / ephemeris path ───────────────────────────────────────────────────
def set_ephe_path(path: str) -> None: ...
def set_sid_mode(sid_mode: int, t0: float, ayan_t0: float) -> None: ...

# ── Vedic ───────────────────────────────────────────────────────────────────────
def vimshottari_dasha(jd_birth: float, moon_lon_sidereal: float, years_ahead: float) -> list[tuple]: ...


# ── Legacy / compatibility aliases ───────────────────────────────────────────

def degnorm(d: float) -> float:
    """Normalise degrees to [0°, 360°). Legacy alias for norm_deg()."""
    ...

def difdeg2n(p1: float, p2: float) -> float:
    """Signed degree difference in (-180°, +180°]. Legacy alias for diff_deg_signed()."""
    ...

def get_ayanamsa(jd_et: float) -> float:
    """Ayanamsa at Julian Day ET. Legacy alias for ayanamsa()."""
    ...

def get_ayanamsa_name(sid_mode: int) -> str:
    """Name of a sidereal mode by SIDM_* constant. Legacy alias for ayanamsa_name()."""
    ...

def next_sabbat_name(jd_from: float) -> str:
    """Name of the next sabbat after jd_from. Legacy alias for next_sabbat()."""
    ...

def next_full_moon(jd_start: float) -> float:
    """JD of the next full moon after jd_start. Legacy alias for next_full_moon_after()."""
    ...

def solcross_ut(x2cross: float, jd_ut: float, flags: int) -> float:
    """JD when the Sun next crosses ecliptic longitude x2cross (UT)."""
    ...
