//! Timezone abbreviation table (port of swhtimezone.c).

/// A timezone abbreviation (e.g. `"UTC"`, `"EST"`) with UTC offset.
pub struct TzAbbr {
    pub name: &'static str,
    pub desc: &'static str,
    /// UTC offset string, e.g. "UTC+05:30".
    pub offset: &'static str,
    pub hours: i32,
    pub minutes: i32,
}

/// Built-in timezone abbreviation table — 203 entries (ported from swhtimezone.c).
/// All timezone abbreviations — 203 entries (source: swhtimezone.c).
pub static TZ_TABLE: &[TzAbbr] = &[
    TzAbbr {
        name: "ACDT",
        desc: "Australian Central Daylight Saving Time",
        offset: "UTC+10:30",
        hours: 10,
        minutes: 30,
    },
    TzAbbr {
        name: "ACST",
        desc: "Australian Central Standard Time",
        offset: "UTC+09:30",
        hours: 9,
        minutes: 30,
    },
    TzAbbr {
        name: "ACT",
        desc: "Acre Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "ADT",
        desc: "Atlantic Daylight Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "AEDT",
        desc: "Australian Eastern Daylight Saving Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "AEST",
        desc: "Australian Eastern Standard Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "AFT",
        desc: "Afghanistan Time",
        offset: "UTC+04:30",
        hours: 4,
        minutes: 30,
    },
    TzAbbr {
        name: "AKDT",
        desc: "Alaska Daylight Time",
        offset: "UTC-08",
        hours: -8,
        minutes: 0,
    },
    TzAbbr {
        name: "AKST",
        desc: "Alaska Standard Time",
        offset: "UTC-09",
        hours: -9,
        minutes: 0,
    },
    TzAbbr {
        name: "ALMT",
        desc: "Alma-Ata Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "AMST",
        desc: "Amazon Summer Time (Brazil)",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "AMT",
        desc: "Amazon Time (Brazil)",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "AMT",
        desc: "Armenia Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "ANAT",
        desc: "Anadyr Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "AQTT",
        desc: "Aqtobe Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "ART",
        desc: "Argentina Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "AST",
        desc: "Arabia Standard Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "AST",
        desc: "Atlantic Standard Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "AWST",
        desc: "Australian Western Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "AZOST",
        desc: "Azores Summer Time",
        offset: "UTC+00",
        hours: 0,
        minutes: 0,
    },
    TzAbbr {
        name: "AZOT",
        desc: "Azores Standard Time",
        offset: "UTC-01",
        hours: -1,
        minutes: 0,
    },
    TzAbbr {
        name: "AZT",
        desc: "Azerbaijan Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "BDT",
        desc: "Brunei Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "BIOT",
        desc: "British Indian Ocean Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "BIT",
        desc: "Baker Island Time",
        offset: "UTC-12",
        hours: -12,
        minutes: 0,
    },
    TzAbbr {
        name: "BOT",
        desc: "Bolivia Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "BRST",
        desc: "Brasilia Summer Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "BRT",
        desc: "Brasilia Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "BST",
        desc: "Bangladesh Standard Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "BST",
        desc: "Bougainville Standard Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "BST",
        desc: "British Summer Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "BTT",
        desc: "Bhutan Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "CAT",
        desc: "Central Africa Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "CCT",
        desc: "Cocos Islands Time",
        offset: "UTC+06:30",
        hours: 6,
        minutes: 30,
    },
    TzAbbr {
        name: "CDT",
        desc: "Central Daylight Time (North America)",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "CDT",
        desc: "Cuba Daylight Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "CEST",
        desc: "Central European Summer Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "CET",
        desc: "Central European Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "CHADT",
        desc: "Chatham Daylight Time",
        offset: "UTC+13:45",
        hours: 13,
        minutes: 45,
    },
    TzAbbr {
        name: "CHAST",
        desc: "Chatham Standard Time",
        offset: "UTC+12:45",
        hours: 12,
        minutes: 45,
    },
    TzAbbr {
        name: "CHOT",
        desc: "Choibalsan Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "CHOST",
        desc: "Choibalsan Summer Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "CHST",
        desc: "Chamorro Standard Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "CHUT",
        desc: "Chuuk Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "CIST",
        desc: "Clipperton Island Standard Time",
        offset: "UTC-08",
        hours: -8,
        minutes: 0,
    },
    TzAbbr {
        name: "CIT",
        desc: "Central Indonesia Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "CKT",
        desc: "Cook Island Time",
        offset: "UTC-10",
        hours: -10,
        minutes: 0,
    },
    TzAbbr {
        name: "CLST",
        desc: "Chile Summer Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "CLT",
        desc: "Chile Standard Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "COST",
        desc: "Colombia Summer Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "COT",
        desc: "Colombia Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "CST",
        desc: "Central Standard Time (North America)",
        offset: "UTC-06",
        hours: -6,
        minutes: 0,
    },
    TzAbbr {
        name: "CST",
        desc: "China Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "CST",
        desc: "Cuba Standard Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "CT",
        desc: "China Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "CVT",
        desc: "Cape Verde Time",
        offset: "UTC-01",
        hours: -1,
        minutes: 0,
    },
    TzAbbr {
        name: "CWST",
        desc: "Central Western Standard Time (Australia)",
        offset: "UTC+08:45",
        hours: 8,
        minutes: 45,
    },
    TzAbbr {
        name: "CXT",
        desc: "Christmas Island Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "DAVT",
        desc: "Davis Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "DDUT",
        desc: "Dumont d'Urville Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "DFT",
        desc: "AIX-specific equivalent of Central European Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "EASST",
        desc: "Easter Island Summer Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "EAST",
        desc: "Easter Island Standard Time",
        offset: "UTC-06",
        hours: -6,
        minutes: 0,
    },
    TzAbbr {
        name: "EAT",
        desc: "East Africa Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "ECT",
        desc: "Eastern Caribbean Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "ECT",
        desc: "Ecuador Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "EDT",
        desc: "Eastern Daylight Time (North America)",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "EEST",
        desc: "Eastern European Summer Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "EET",
        desc: "Eastern European Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "EGST",
        desc: "Eastern Greenland Summer Time",
        offset: "UTC+00",
        hours: 0,
        minutes: 0,
    },
    TzAbbr {
        name: "EGT",
        desc: "Eastern Greenland Time",
        offset: "UTC-01",
        hours: -1,
        minutes: 0,
    },
    TzAbbr {
        name: "EIT",
        desc: "Eastern Indonesian Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "EST",
        desc: "Eastern Standard Time (North America)",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "FET",
        desc: "Further-eastern European Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "FJT",
        desc: "Fiji Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "FKST",
        desc: "Falkland Islands Summer Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "FKT",
        desc: "Falkland Islands Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "FNT",
        desc: "Fernando de Noronha Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "GALT",
        desc: "Galapagos Time",
        offset: "UTC-06",
        hours: -6,
        minutes: 0,
    },
    TzAbbr {
        name: "GAMT",
        desc: "Gambier Islands Time",
        offset: "UTC-09",
        hours: -9,
        minutes: 0,
    },
    TzAbbr {
        name: "GET",
        desc: "Georgia Standard Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "GFT",
        desc: "French Guiana Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "GILT",
        desc: "Gilbert Island Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "GIT",
        desc: "Gambier Island Time",
        offset: "UTC-09",
        hours: -9,
        minutes: 0,
    },
    TzAbbr {
        name: "GMT",
        desc: "Greenwich Mean Time",
        offset: "UTC+00",
        hours: 0,
        minutes: 0,
    },
    TzAbbr {
        name: "GST",
        desc: "South Georgia and South Sandwich Islands Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "GST",
        desc: "Gulf Standard Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "GYT",
        desc: "Guyana Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "HDT",
        desc: "Hawaii-Aleutian Daylight Time",
        offset: "UTC-09",
        hours: -9,
        minutes: 0,
    },
    TzAbbr {
        name: "HAEC",
        desc: "Heure Avancee d'Europe Centrale (CEST)",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "HST",
        desc: "Hawaii-Aleutian Standard Time",
        offset: "UTC-10",
        hours: -10,
        minutes: 0,
    },
    TzAbbr {
        name: "HKT",
        desc: "Hong Kong Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "HMT",
        desc: "Heard and McDonald Islands Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "HOVST",
        desc: "Hovd Summer Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "HOVT",
        desc: "Hovd Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "ICT",
        desc: "Indochina Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "IDLW",
        desc: "International Day Line West time zone",
        offset: "UTC-12",
        hours: -12,
        minutes: 0,
    },
    TzAbbr {
        name: "IDT",
        desc: "Israel Daylight Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "IOT",
        desc: "Indian Ocean Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "IRDT",
        desc: "Iran Daylight Time",
        offset: "UTC+04:30",
        hours: 4,
        minutes: 30,
    },
    TzAbbr {
        name: "IRKT",
        desc: "Irkutsk Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "IRST",
        desc: "Iran Standard Time",
        offset: "UTC+03:30",
        hours: 3,
        minutes: 30,
    },
    TzAbbr {
        name: "IST",
        desc: "Indian Standard Time",
        offset: "UTC+05:30",
        hours: 5,
        minutes: 30,
    },
    TzAbbr {
        name: "IST",
        desc: "Irish Standard Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "IST",
        desc: "Israel Standard Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "JST",
        desc: "Japan Standard Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "KALT",
        desc: "Kaliningrad Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "KGT",
        desc: "Kyrgyzstan Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "KOST",
        desc: "Kosrae Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "KRAT",
        desc: "Krasnoyarsk Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "KST",
        desc: "Korea Standard Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "LHST",
        desc: "Lord Howe Standard Time",
        offset: "UTC+10:30",
        hours: 10,
        minutes: 30,
    },
    TzAbbr {
        name: "LHST",
        desc: "Lord Howe Summer Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "LINT",
        desc: "Line Islands Time",
        offset: "UTC+14",
        hours: 14,
        minutes: 0,
    },
    TzAbbr {
        name: "MAGT",
        desc: "Magadan Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "MART",
        desc: "Marquesas Islands Time",
        offset: "UTC-09:30",
        hours: -9,
        minutes: 30,
    },
    TzAbbr {
        name: "MAWT",
        desc: "Mawson Station Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "MDT",
        desc: "Mountain Daylight Time (North America)",
        offset: "UTC-06",
        hours: -6,
        minutes: 0,
    },
    TzAbbr {
        name: "MET",
        desc: "Middle European Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "MEST",
        desc: "Middle European Summer Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "MHT",
        desc: "Marshall Islands Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "MIST",
        desc: "Macquarie Island Station Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "MIT",
        desc: "Marquesas Islands Time",
        offset: "UTC-09:30",
        hours: -9,
        minutes: 30,
    },
    TzAbbr {
        name: "MMT",
        desc: "Myanmar Standard Time",
        offset: "UTC+06:30",
        hours: 6,
        minutes: 30,
    },
    TzAbbr {
        name: "MSK",
        desc: "Moscow Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "MST",
        desc: "Malaysia Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "MST",
        desc: "Mountain Standard Time (North America)",
        offset: "UTC-07",
        hours: -7,
        minutes: 0,
    },
    TzAbbr {
        name: "MUT",
        desc: "Mauritius Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "MVT",
        desc: "Maldives Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "MYT",
        desc: "Malaysia Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "NCT",
        desc: "New Caledonia Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "NDT",
        desc: "Newfoundland Daylight Time",
        offset: "UTC-02:30",
        hours: -2,
        minutes: 30,
    },
    TzAbbr {
        name: "NFT",
        desc: "Norfolk Island Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "NOVT",
        desc: "Novosibirsk Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "NPT",
        desc: "Nepal Time",
        offset: "UTC+05:45",
        hours: 5,
        minutes: 45,
    },
    TzAbbr {
        name: "NST",
        desc: "Newfoundland Standard Time",
        offset: "UTC-03:30",
        hours: -3,
        minutes: 30,
    },
    TzAbbr {
        name: "NT",
        desc: "Newfoundland Time",
        offset: "UTC-03:30",
        hours: -3,
        minutes: 30,
    },
    TzAbbr {
        name: "NUT",
        desc: "Niue Time",
        offset: "UTC-11",
        hours: -11,
        minutes: 0,
    },
    TzAbbr {
        name: "NZDT",
        desc: "New Zealand Daylight Time",
        offset: "UTC+13",
        hours: 13,
        minutes: 0,
    },
    TzAbbr {
        name: "NZST",
        desc: "New Zealand Standard Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "OMST",
        desc: "Omsk Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "ORAT",
        desc: "Oral Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "PDT",
        desc: "Pacific Daylight Time (North America)",
        offset: "UTC-07",
        hours: -7,
        minutes: 0,
    },
    TzAbbr {
        name: "PET",
        desc: "Peru Time",
        offset: "UTC-05",
        hours: -5,
        minutes: 0,
    },
    TzAbbr {
        name: "PETT",
        desc: "Kamchatka Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "PGT",
        desc: "Papua New Guinea Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "PHOT",
        desc: "Phoenix Island Time",
        offset: "UTC+13",
        hours: 13,
        minutes: 0,
    },
    TzAbbr {
        name: "PHT",
        desc: "Philippine Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "PKT",
        desc: "Pakistan Standard Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "PMDT",
        desc: "Saint Pierre and Miquelon Daylight Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "PMST",
        desc: "Saint Pierre and Miquelon Standard Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "PONT",
        desc: "Pohnpei Standard Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "PST",
        desc: "Pacific Standard Time (North America)",
        offset: "UTC-08",
        hours: -8,
        minutes: 0,
    },
    TzAbbr {
        name: "PST",
        desc: "Philippine Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "PYST",
        desc: "Paraguay Summer Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "PYT",
        desc: "Paraguay Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "RET",
        desc: "Reunion Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "ROTT",
        desc: "Rothera Research Station Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "SAKT",
        desc: "Sakhalin Island Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "SAMT",
        desc: "Samara Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "SAST",
        desc: "South African Standard Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "SBT",
        desc: "Solomon Islands Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "SCT",
        desc: "Seychelles Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "SDT",
        desc: "Samoa Daylight Time",
        offset: "UTC-10",
        hours: -10,
        minutes: 0,
    },
    TzAbbr {
        name: "SGT",
        desc: "Singapore Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "SLST",
        desc: "Sri Lanka Standard Time",
        offset: "UTC+05:30",
        hours: 5,
        minutes: 30,
    },
    TzAbbr {
        name: "SRET",
        desc: "Srednekolymsk Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "SRT",
        desc: "Suriname Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "SST",
        desc: "Samoa Standard Time",
        offset: "UTC-11",
        hours: -11,
        minutes: 0,
    },
    TzAbbr {
        name: "SST",
        desc: "Singapore Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "SYOT",
        desc: "Showa Station Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "TAHT",
        desc: "Tahiti Time",
        offset: "UTC-10",
        hours: -10,
        minutes: 0,
    },
    TzAbbr {
        name: "THA",
        desc: "Thailand Standard Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "TFT",
        desc: "French Southern and Antarctic Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "TJT",
        desc: "Tajikistan Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "TKT",
        desc: "Tokelau Time",
        offset: "UTC+13",
        hours: 13,
        minutes: 0,
    },
    TzAbbr {
        name: "TLT",
        desc: "Timor Leste Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "TMT",
        desc: "Turkmenistan Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "TRT",
        desc: "Turkey Time",
        offset: "UTC+03",
        hours: 3,
        minutes: 0,
    },
    TzAbbr {
        name: "TOT",
        desc: "Tonga Time",
        offset: "UTC+13",
        hours: 13,
        minutes: 0,
    },
    TzAbbr {
        name: "TVT",
        desc: "Tuvalu Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "ULAST",
        desc: "Ulaanbaatar Summer Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "ULAT",
        desc: "Ulaanbaatar Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "UTC",
        desc: "Coordinated Universal Time",
        offset: "UTC+00",
        hours: 0,
        minutes: 0,
    },
    TzAbbr {
        name: "UYST",
        desc: "Uruguay Summer Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "UYT",
        desc: "Uruguay Standard Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "UZT",
        desc: "Uzbekistan Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
    TzAbbr {
        name: "VET",
        desc: "Venezuelan Standard Time",
        offset: "UTC-04",
        hours: -4,
        minutes: 0,
    },
    TzAbbr {
        name: "VLAT",
        desc: "Vladivostok Time",
        offset: "UTC+10",
        hours: 10,
        minutes: 0,
    },
    TzAbbr {
        name: "VOLT",
        desc: "Volgograd Time",
        offset: "UTC+04",
        hours: 4,
        minutes: 0,
    },
    TzAbbr {
        name: "VOST",
        desc: "Vostok Station Time",
        offset: "UTC+06",
        hours: 6,
        minutes: 0,
    },
    TzAbbr {
        name: "VUT",
        desc: "Vanuatu Time",
        offset: "UTC+11",
        hours: 11,
        minutes: 0,
    },
    TzAbbr {
        name: "WAKT",
        desc: "Wake Island Time",
        offset: "UTC+12",
        hours: 12,
        minutes: 0,
    },
    TzAbbr {
        name: "WAST",
        desc: "West Africa Summer Time",
        offset: "UTC+02",
        hours: 2,
        minutes: 0,
    },
    TzAbbr {
        name: "WAT",
        desc: "West Africa Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "WEST",
        desc: "Western European Summer Time",
        offset: "UTC+01",
        hours: 1,
        minutes: 0,
    },
    TzAbbr {
        name: "WET",
        desc: "Western European Time",
        offset: "UTC+00",
        hours: 0,
        minutes: 0,
    },
    TzAbbr {
        name: "WIT",
        desc: "Western Indonesian Time",
        offset: "UTC+07",
        hours: 7,
        minutes: 0,
    },
    TzAbbr {
        name: "WGST",
        desc: "West Greenland Summer Time",
        offset: "UTC-02",
        hours: -2,
        minutes: 0,
    },
    TzAbbr {
        name: "WGT",
        desc: "West Greenland Time",
        offset: "UTC-03",
        hours: -3,
        minutes: 0,
    },
    TzAbbr {
        name: "WST",
        desc: "Western Standard Time",
        offset: "UTC+08",
        hours: 8,
        minutes: 0,
    },
    TzAbbr {
        name: "YAKT",
        desc: "Yakutsk Time",
        offset: "UTC+09",
        hours: 9,
        minutes: 0,
    },
    TzAbbr {
        name: "YEKT",
        desc: "Yekaterinburg Time",
        offset: "UTC+05",
        hours: 5,
        minutes: 0,
    },
];

/// Find timezone entries by abbreviation (case-insensitive).
/// Returns all matching entries (multiple countries may share an abbreviation).
#[must_use]
pub fn tz_abbr_find(abbr: &str) -> Vec<&'static TzAbbr> {
    let lower = abbr.to_ascii_uppercase();
    TZ_TABLE
        .iter()
        .filter(|tz| tz.name == lower.as_str())
        .collect()
}
